// Generated by shared/mcp-icons/sync.mjs; edit shared/mcp-icons/catalog.json.
package ai.oriveo.community.core.mcp

import ai.oriveo.community.R
import java.net.URI
import java.util.Locale

object McpBrandIcons {
    private data class Brand(val key: String, val names: Set<String>, val hosts: Set<String>, val light: Int, val dark: Int)
    private val brands = listOf(
        Brand("deepwiki", setOf("deepwiki", "deep wiki", "cognition", "devin"), setOf("deepwiki.com", "devin.ai", "cognition.ai"), R.drawable.mcp_brand_deepwiki_light, R.drawable.mcp_brand_deepwiki_dark),
        Brand("context7", setOf("context7", "context 7"), setOf("context7.com"), R.drawable.mcp_brand_context7_light, R.drawable.mcp_brand_context7_dark),
        Brand("github", setOf("github", "github copilot"), setOf("github.com", "githubcopilot.com"), R.drawable.mcp_brand_github_light, R.drawable.mcp_brand_github_dark),
        Brand("notion", setOf("notion"), setOf("notion.so", "notion.com"), R.drawable.mcp_brand_notion_light, R.drawable.mcp_brand_notion_dark),
        Brand("figma", setOf("figma"), setOf("figma.com"), R.drawable.mcp_brand_figma_light, R.drawable.mcp_brand_figma_dark),
        Brand("brave", setOf("brave", "brave search"), setOf("brave.com"), R.drawable.mcp_brand_brave_light, R.drawable.mcp_brand_brave_dark),
        Brand("tavily", setOf("tavily"), setOf("tavily.com"), R.drawable.mcp_brand_tavily_light, R.drawable.mcp_brand_tavily_dark),
        Brand("exa", setOf("exa"), setOf("exa.ai"), R.drawable.mcp_brand_exa_light, R.drawable.mcp_brand_exa_dark),
        Brand("firecrawl", setOf("firecrawl"), setOf("firecrawl.dev"), R.drawable.mcp_brand_firecrawl_light, R.drawable.mcp_brand_firecrawl_dark),
        Brand("jina", setOf("jina", "jina ai"), setOf("jina.ai"), R.drawable.mcp_brand_jina_light, R.drawable.mcp_brand_jina_dark),
        Brand("perplexity", setOf("perplexity"), setOf("perplexity.ai"), R.drawable.mcp_brand_perplexity_light, R.drawable.mcp_brand_perplexity_dark),
        Brand("vercel", setOf("vercel"), setOf("vercel.com"), R.drawable.mcp_brand_vercel_light, R.drawable.mcp_brand_vercel_dark),
        Brand("cloudflare", setOf("cloudflare"), setOf("cloudflare.com"), R.drawable.mcp_brand_cloudflare_light, R.drawable.mcp_brand_cloudflare_dark),
        Brand("microsoft", setOf("microsoft", "azure"), setOf("microsoft.com", "azure.com"), R.drawable.mcp_brand_microsoft_light, R.drawable.mcp_brand_microsoft_dark),
        Brand("googlecloud", setOf("google cloud", "gcp"), setOf("cloud.google.com", "googleapis.com"), R.drawable.mcp_brand_googlecloud_light, R.drawable.mcp_brand_googlecloud_dark),
        Brand("huggingface", setOf("hugging face", "huggingface"), setOf("huggingface.co"), R.drawable.mcp_brand_huggingface_light, R.drawable.mcp_brand_huggingface_dark),
        Brand("browserless", setOf("browserless"), setOf("browserless.io"), R.drawable.mcp_brand_browserless_light, R.drawable.mcp_brand_browserless_dark),
        Brand("slack", setOf("slack"), setOf("slack.com"), R.drawable.mcp_brand_slack_light, R.drawable.mcp_brand_slack_dark),
        Brand("linear", setOf("linear"), setOf("linear.app"), R.drawable.mcp_brand_linear_light, R.drawable.mcp_brand_linear_dark),
        Brand("googledrive", setOf("google drive", "gdrive"), setOf("drive.google.com"), R.drawable.mcp_brand_googledrive_light, R.drawable.mcp_brand_googledrive_dark),
        Brand("sentry", setOf("sentry"), setOf("sentry.io"), R.drawable.mcp_brand_sentry_light, R.drawable.mcp_brand_sentry_dark),
        Brand("stripe", setOf("stripe"), setOf("stripe.com"), R.drawable.mcp_brand_stripe_light, R.drawable.mcp_brand_stripe_dark),
        Brand("airtable", setOf("airtable"), setOf("airtable.com"), R.drawable.mcp_brand_airtable_light, R.drawable.mcp_brand_airtable_dark),
        Brand("supabase", setOf("supabase"), setOf("supabase.com", "supabase.co"), R.drawable.mcp_brand_supabase_light, R.drawable.mcp_brand_supabase_dark),
        Brand("neon", setOf("neon", "neon postgres"), setOf("neon.tech", "neon.com"), R.drawable.mcp_brand_neon_light, R.drawable.mcp_brand_neon_dark),
        Brand("jira", setOf("jira"), setOf("jira.com"), R.drawable.mcp_brand_jira_light, R.drawable.mcp_brand_jira_dark),
        Brand("atlassian", setOf("atlassian"), setOf("atlassian.com", "atlassian.net"), R.drawable.mcp_brand_atlassian_light, R.drawable.mcp_brand_atlassian_dark),
        Brand("dropbox", setOf("dropbox"), setOf("dropbox.com"), R.drawable.mcp_brand_dropbox_light, R.drawable.mcp_brand_dropbox_dark),
        Brand("docker", setOf("docker"), setOf("docker.com"), R.drawable.mcp_brand_docker_light, R.drawable.mcp_brand_docker_dark),
        Brand("postgresql", setOf("postgres", "postgresql"), setOf("postgresql.org"), R.drawable.mcp_brand_postgresql_light, R.drawable.mcp_brand_postgresql_dark),
        Brand("redis", setOf("redis"), setOf("redis.io", "redis.com"), R.drawable.mcp_brand_redis_light, R.drawable.mcp_brand_redis_dark),
        Brand("mongodb", setOf("mongodb", "mongo db"), setOf("mongodb.com", "mongodb.net"), R.drawable.mcp_brand_mongodb_light, R.drawable.mcp_brand_mongodb_dark),
        Brand("snowflake", setOf("snowflake"), setOf("snowflake.com"), R.drawable.mcp_brand_snowflake_light, R.drawable.mcp_brand_snowflake_dark),
        Brand("elastic", setOf("elastic", "elasticsearch"), setOf("elastic.co"), R.drawable.mcp_brand_elastic_light, R.drawable.mcp_brand_elastic_dark),
        Brand("grafana", setOf("grafana"), setOf("grafana.com", "grafana.net"), R.drawable.mcp_brand_grafana_light, R.drawable.mcp_brand_grafana_dark),
        Brand("gitlab", setOf("gitlab"), setOf("gitlab.com"), R.drawable.mcp_brand_gitlab_light, R.drawable.mcp_brand_gitlab_dark),
        Brand("asana", setOf("asana"), setOf("asana.com"), R.drawable.mcp_brand_asana_light, R.drawable.mcp_brand_asana_dark),
        Brand("todoist", setOf("todoist"), setOf("todoist.com"), R.drawable.mcp_brand_todoist_light, R.drawable.mcp_brand_todoist_dark),
        Brand("zapier", setOf("zapier"), setOf("zapier.com"), R.drawable.mcp_brand_zapier_light, R.drawable.mcp_brand_zapier_dark),
        Brand("n8n", setOf("n8n"), setOf("n8n.io", "n8n.cloud"), R.drawable.mcp_brand_n8n_light, R.drawable.mcp_brand_n8n_dark),
        Brand("wikipedia", setOf("wikipedia", "wiki"), setOf("wikipedia.org"), R.drawable.mcp_brand_wikipedia_light, R.drawable.mcp_brand_wikipedia_dark),
        Brand("gitbook", setOf("gitbook"), setOf("gitbook.com", "gitbook.io"), R.drawable.mcp_brand_gitbook_light, R.drawable.mcp_brand_gitbook_dark),
        Brand("confluence", setOf("confluence"), setOf("confluence.com"), R.drawable.mcp_brand_confluence_light, R.drawable.mcp_brand_confluence_dark),
        Brand("clickup", setOf("clickup", "click up"), setOf("clickup.com"), R.drawable.mcp_brand_clickup_light, R.drawable.mcp_brand_clickup_dark),
        Brand("trello", setOf("trello"), setOf("trello.com"), R.drawable.mcp_brand_trello_light, R.drawable.mcp_brand_trello_dark),
        Brand("zendesk", setOf("zendesk"), setOf("zendesk.com"), R.drawable.mcp_brand_zendesk_light, R.drawable.mcp_brand_zendesk_dark),
        Brand("intercom", setOf("intercom"), setOf("intercom.com", "intercom.io"), R.drawable.mcp_brand_intercom_light, R.drawable.mcp_brand_intercom_dark),
        Brand("shopify", setOf("shopify"), setOf("shopify.com", "myshopify.com"), R.drawable.mcp_brand_shopify_light, R.drawable.mcp_brand_shopify_dark),
        Brand("hubspot", setOf("hubspot"), setOf("hubspot.com"), R.drawable.mcp_brand_hubspot_light, R.drawable.mcp_brand_hubspot_dark),
        Brand("resend", setOf("resend"), setOf("resend.com"), R.drawable.mcp_brand_resend_light, R.drawable.mcp_brand_resend_dark),
        Brand("box", setOf("box"), setOf("box.com"), R.drawable.mcp_brand_box_light, R.drawable.mcp_brand_box_dark),
        Brand("datadog", setOf("datadog"), setOf("datadoghq.com", "datadoghq.eu"), R.drawable.mcp_brand_datadog_light, R.drawable.mcp_brand_datadog_dark),
        Brand("digitalocean", setOf("digitalocean", "digital ocean"), setOf("digitalocean.com"), R.drawable.mcp_brand_digitalocean_light, R.drawable.mcp_brand_digitalocean_dark),
        Brand("bitbucket", setOf("bitbucket"), setOf("bitbucket.org"), R.drawable.mcp_brand_bitbucket_light, R.drawable.mcp_brand_bitbucket_dark),
        Brand("mysql", setOf("mysql"), setOf("mysql.com"), R.drawable.mcp_brand_mysql_light, R.drawable.mcp_brand_mysql_dark),
        Brand("sqlite", setOf("sqlite"), setOf("sqlite.org"), R.drawable.mcp_brand_sqlite_light, R.drawable.mcp_brand_sqlite_dark),
        Brand("duckdb", setOf("duckdb"), setOf("duckdb.org"), R.drawable.mcp_brand_duckdb_light, R.drawable.mcp_brand_duckdb_dark),
        Brand("kubernetes", setOf("kubernetes", "k8s"), setOf("kubernetes.io"), R.drawable.mcp_brand_kubernetes_light, R.drawable.mcp_brand_kubernetes_dark),
        Brand("postman", setOf("postman"), setOf("postman.com"), R.drawable.mcp_brand_postman_light, R.drawable.mcp_brand_postman_dark),
        Brand("zoom", setOf("zoom"), setOf("zoom.us"), R.drawable.mcp_brand_zoom_light, R.drawable.mcp_brand_zoom_dark),
        Brand("obsidian", setOf("obsidian"), setOf("obsidian.md"), R.drawable.mcp_brand_obsidian_light, R.drawable.mcp_brand_obsidian_dark),
        Brand("algolia", setOf("algolia"), setOf("algolia.com", "algolia.net"), R.drawable.mcp_brand_algolia_light, R.drawable.mcp_brand_algolia_dark),
        Brand("netlify", setOf("netlify"), setOf("netlify.com"), R.drawable.mcp_brand_netlify_light, R.drawable.mcp_brand_netlify_dark),
    )

    val keys: List<String> get() = brands.map { it.key }

    fun key(name: String, serverUrl: String? = null): String? {
        val host = runCatching { URI(serverUrl ?: "").takeIf { it.scheme.equals("https", ignoreCase = true) }?.host?.lowercase(Locale.ROOT)?.removeSuffix(".") }.getOrNull()
        val hostMatch = brands.flatMap { brand -> brand.hosts.map { brand to it } }
            .filter { (_, domain) -> host == domain || host?.endsWith("." + domain) == true }
            .maxByOrNull { (_, domain) -> domain.length }
        if (hostMatch != null) return hostMatch.first.key
        val normalized = name.trim().lowercase(Locale.ROOT).replace(Regex("[._-]+"), " ").replace(Regex("\\s+"), " ")
            .replace(Regex("^mcp(?: server)? "), "").replace(Regex(" (?:mcp(?: server)?|server)$"), "")
        return brands.firstOrNull { normalized == it.key || normalized.replace(" ", "") == it.key || normalized in it.names }?.key
    }

    fun drawable(name: String, serverUrl: String? = null, dark: Boolean = false): Int? {
        val key = key(name, serverUrl) ?: return null
        val brand = brands.first { it.key == key }
        return if (dark) brand.dark else brand.light
    }
}
