import type {
  ChatRole,
  ReasoningMode,
  RelayKeyValue,
  RelayWebSearchToolName,
} from '@oriveo/shared/pure-types';
import type { OfficialProviderKind, RelayEndpointContract } from './provider';

export type GenerationParameterWireValue = number | string | boolean | string[] | Record<string, unknown>;
export type GenerationParameterWireOverride =
  | { state: 'inherit' }
  | { state: 'omit' }
  | { state: 'value'; value: GenerationParameterWireValue };

export type ChatContentPart =
  | { type: 'text'; text: string }
  | {
      type: 'image';
      imageRef: string;
      mimeType?: string;
      /** OpenAI vision detail level; only openai_chat/openai_responses consume it, other transports ignore it. */
      detail?: 'auto' | 'low' | 'high';
    }
  | { type: 'video'; videoRef: string; mimeType?: string }
  | {
      type: 'file';
      fileName: string;
      mimeType: string;
      dataRef: string;
      // Attachment extraction metadata: block headers built by AttachmentInjector, plus the native fallback source marker.
      extractedTotalLines?: number;
      extractedTruncated?: boolean;
      extractedSizeBytes?: number;
      extractionErrorCode?: string;
    };

export interface ChatRequestMessage {
  role: Extract<ChatRole, 'system' | 'user' | 'assistant'> | 'tool';
  content: string | ChatContentPart[];
  toolCallId?: string;
}

/**
 * Connection-level identity for the negative cache that recovers from rejected parameters.
 * Only the renderer has it: the partition and the connection/credential epochs live in
 * renderer-local storage and the two revisions come from the renderer's metadata client, so
 * the main process cannot rebuild them and they travel over IPC with the request. All of it
 * is irreversible local opaque identifiers, with no key, URL or credential.
 */
export interface ChatCapabilityIdentity {
  partitionId: string;
  connectionInstanceId: string;
  connectionGeneration: string;
  credentialEpoch: string;
  metadataRevision: string;
  generationRevision: string;
}

export interface ChatStreamOptions {
  temperature?: number;
  maxOutputTokens?: number;
  reasoningMode?: ReasoningMode;
  webSearchEnabled?: boolean;
  /** Image generation switch; the official openai/gemini/siliconflow builders use it to take the image generation request path. */
  imageGenEnabled?: boolean;
  /** Generation parameter intent already resolved against the renderer-local scope; main only forwards it to the core builder and never persists it. */
  generationParameters?: Record<string, GenerationParameterWireOverride | undefined>;
  /** Relay advanced mode options, consumed only by relay and ignored by official providers. */
  relayServiceTier?: string;
  relayReasoningEffort?: 'low' | 'medium' | 'high' | 'xhigh';
  relayStream?: boolean;
  /** disable_response_storage as enabled by the user in advanced mode; forwarded only on the Responses transport. */
  relayDisableResponseStorage?: boolean;
  /** Web search tool protocol name for Codex/openai_responses; the adapter falls back to 'web_search', and 'disabled' means no tool is attached. */
  relayWebSearchToolName?: RelayWebSearchToolName;
  /** Relay custom auth and request headers, query parameters, codex identity and UA; consumed by buildRelayProxyConfig, relay only. */
  relayHeaders?: RelayKeyValue[];
  relayQueryParams?: RelayKeyValue[];
  relayCodexCompatIdentity?: boolean;
  relayCustomUserAgent?: string;
  /** See {@link ChatCapabilityIdentity}; when absent the negative cache on the main side fails closed and retries each request separately. */
  capabilityIdentity?: ChatCapabilityIdentity;
  abortSignalId?: string;
}

export interface ChatStreamRequestBase {
  conversationId: string;
  modelID: string;
  apiKeyRef: string;
  messages: ChatRequestMessage[];
  options?: ChatStreamOptions;
}

export interface OfficialChatStreamRequest extends ChatStreamRequestBase {
  providerKind: OfficialProviderKind;
  relay?: never;
  /** Custom endpoint override for an official provider (self-hosted, openai-compatible or proxied); empty falls back to the kind's default endpoint. */
  baseURL?: string;
}

export interface RelayChatStreamRequest extends ChatStreamRequestBase {
  providerKind: 'relay';
  relay: RelayEndpointContract;
  baseURL?: never;
}

export type ChatStreamRequest = OfficialChatStreamRequest | RelayChatStreamRequest;

/**
 * The preload `window.oriveo.chat` bridge. streamId is generated by the renderer and serves
 * as both the idempotency key and the port claim key.
 *
 * Port transfer follows the Electron pattern, since contextBridge cannot carry a
 * MessagePort: preload creates a MessageChannel, sends port2 to main through
 * ipcRenderer.postMessage(chat:stream:start,[port2]) and hands port1 to the renderer main
 * world through window.postMessage(..,[port1]) to be claimed. That is why startStream does
 * not return a port.
 * Events arrive over the port as ChatStreamEnvelope/ChatStreamClosed, whose types live in
 * @oriveo/core/chat/ipc-stream because they reference StreamEvent and cannot live in this
 * contract package.
 */
export interface OriveoChatBridge {
  startStream(streamId: string, req: ChatStreamRequest): void;
  cancelStream(streamId: string): void;
}
