import type { LucideIcon } from 'lucide-react';
import {
  SquarePen,
  Pencil,
  FileText,
  Files,
  Scroll,
  StickyNote,
  CircleCheck,
  Check,
  XCircle,
  Search,
  ListChecks,
  SquareCheck,
  Globe,
  Map,
  Languages,
  Type,
  Laptop,
  Monitor,
  Keyboard,
  Database,
  HardDrive,
  Disc,
  Bug,
  Bot,
  Settings,
  Wrench,
  Hammer,
  PenTool,
  BarChart3,
  TrendingUp,
  TrendingDown,
  Lightbulb,
  Sparkles,
  Palette,
  Target,
  Brain,
  Star,
  GraduationCap,
  BookOpen,
  Briefcase,
  DollarSign,
  Receipt,
  Calendar,
  AlarmClock,
  Timer,
  Clock,
  Hourglass,
  Mail,
  MailOpen,
  MessageSquare,
  MessageCircle,
  Phone,
  Smartphone,
  ShieldCheck,
  Lock,
  LockOpen,
  Shield,
  Key,
  Hospital,
  Pill,
  Heart,
  Stethoscope,
  Plane,
  Car,
  Home,
  Building,
  Building2,
  Rocket,
  Folder,
  FolderPlus,
  Pin,
  MapPin,
  Bookmark,
  Tag,
  Film,
  Video,
  Music,
  Mic,
  Headphones,
  Camera,
  Tv,
  Gamepad2,
  Utensils,
  Coffee,
  Scale,
  Leaf,
  Trees,
  Sun,
  Moon,
  CloudRain,
  CloudLightning,
  Snowflake,
  Flame,
  Droplet,
  Calculator,
  Hash,
  Ruler,
  User,
  Users,
  UserCog,
  Newspaper,
  Trophy,
  Medal,
  AlertTriangle,
  HelpCircle,
  AlertCircle,
  Info,
} from 'lucide-react';

/**
 * Emoji to Lucide icon mapping.
 *
 * Design rules:
 * - a hit renders the vector Lucide icon, which is crisper, consistent and tintable
 * - a miss falls back to the original emoji, so custom ones still work
 * - matches with or without the variation selector (FE0F)
 */
const MAPPING: Readonly<Record<string, LucideIcon>> = {
  // Writing and creation
  '✍️': SquarePen,
  '✍': SquarePen,
  '✏️': Pencil,
  '✏': Pencil,
  '🖊️': Pencil,
  '🖋️': PenTool,
  '📝': SquarePen,
  '📄': FileText,
  '📃': FileText,
  '📑': Files,
  '📜': Scroll,
  '🗒️': StickyNote,

  // Proofreading and checking
  '✅': CircleCheck,
  '✔️': Check,
  '✔': Check,
  '❌': XCircle,
  '🔍': Search,
  '🔎': Search,
  '📋': ListChecks,
  '☑️': SquareCheck,

  // Translation and the world
  '🌐': Globe,
  '🌍': Globe,
  '🌎': Globe,
  '🌏': Globe,
  '🗺️': Map,
  '🗺': Map,
  '🔤': Type,
  '🔡': Type,
  '🔠': Languages,

  // Programming and development
  '💻': Laptop,
  '🖥️': Monitor,
  '🖥': Monitor,
  '⌨️': Keyboard,
  '⌨': Keyboard,
  '🗄️': Database,
  '🗄': Database,
  '💾': HardDrive,
  '💿': Disc,
  '📀': Disc,
  '🐛': Bug,
  '🤖': Bot,
  '⚙️': Settings,
  '⚙': Settings,
  '🔧': Wrench,
  '🔨': Hammer,
  '🛠️': Wrench,
  '🛠': Wrench,
  '🧰': Wrench,

  // Data and charts
  '📊': BarChart3,
  '📈': TrendingUp,
  '📉': TrendingDown,

  // Ideas and creativity
  '💡': Lightbulb,
  '✨': Sparkles,
  '🎨': Palette,
  '🎯': Target,
  '🧠': Brain,
  '🌟': Star,
  '⭐': Star,
  '⭐️': Star,

  // Learning and education
  '🎓': GraduationCap,
  '📚': BookOpen,
  '📖': BookOpen,
  '📕': BookOpen,
  '📗': BookOpen,
  '📘': BookOpen,
  '📙': BookOpen,
  '🏫': GraduationCap,

  // Business
  '💼': Briefcase,
  '💰': DollarSign,
  '💵': DollarSign,
  '💸': DollarSign,
  '💹': TrendingUp,
  '🧾': Receipt,

  // Time
  '📅': Calendar,
  '📆': Calendar,
  '🗓️': Calendar,
  '🗓': Calendar,
  '⏰': AlarmClock,
  '⏱️': Timer,
  '⏱': Timer,
  '⏲️': Timer,
  '🕐': Clock,
  '⌛': Hourglass,
  '⏳': Hourglass,

  // Communication and messaging
  '📧': Mail,
  '📨': MailOpen,
  '📩': Mail,
  '✉️': Mail,
  '✉': Mail,
  '📞': Phone,
  '📱': Smartphone,
  '💬': MessageSquare,
  '💭': MessageCircle,
  '🗨️': MessageSquare,
  '🗨': MessageSquare,
  '🗯️': AlertCircle,
  '🗣️': MessageCircle,
  '🗣': MessageCircle,

  // Security and locks
  '🔐': ShieldCheck,
  '🔒': Lock,
  '🔓': LockOpen,
  '🛡️': Shield,
  '🛡': Shield,
  '🔑': Key,
  '🗝️': Key,

  // Health and medicine
  '🏥': Hospital,
  '💊': Pill,
  '❤️': Heart,
  '❤': Heart,
  '🩺': Stethoscope,

  // Travel and geography
  '✈️': Plane,
  '✈': Plane,
  '🚗': Car,
  '🚕': Car,
  '🏠': Home,
  '🏡': Home,
  '🏢': Building,
  '🏨': Building2,
  '🚀': Rocket,

  // Files and folders
  '📁': Folder,
  '📂': FolderPlus,
  '🗂️': Folder,
  '🗂': Folder,
  '📌': Pin,
  '📍': MapPin,
  '🔖': Bookmark,
  '🏷️': Tag,
  '🏷': Tag,

  // Media
  '🎬': Film,
  '🎥': Video,
  '📽️': Film,
  '📽': Film,
  '🎵': Music,
  '🎶': Music,
  '🎤': Mic,
  '🎧': Headphones,
  '📷': Camera,
  '📸': Camera,
  '📹': Video,
  '📺': Tv,
  '🎮': Gamepad2,

  // Food and drink
  '🍽️': Utensils,
  '🍽': Utensils,
  '☕': Coffee,
  '🍵': Coffee,
  '🍳': Utensils,

  // Law and ethics
  '⚖️': Scale,
  '⚖': Scale,

  // Nature and weather
  '🌿': Leaf,
  '🍃': Leaf,
  '🌳': Trees,
  '🌲': Trees,
  '☀️': Sun,
  '☀': Sun,
  '🌙': Moon,
  '🌧️': CloudRain,
  '⛈️': CloudLightning,
  '❄️': Snowflake,
  '❄': Snowflake,
  '🔥': Flame,
  '💧': Droplet,

  // Numbers and maths
  '🧮': Calculator,
  '➕': Calculator,
  '➖': Calculator,
  '✖️': Calculator,
  '✖': Calculator,
  '➗': Calculator,
  '🔢': Hash,
  '📐': Ruler,
  '📏': Ruler,

  // Users and people
  '👤': User,
  '👥': Users,
  '🧑‍💻': UserCog,
  '👨‍🏫': GraduationCap,
  '👩‍🏫': GraduationCap,
  '👨‍🍳': Utensils,
  '👨‍⚕️': Stethoscope,
  '🧑‍🎨': Palette,

  // Everything else in common use
  '📰': Newspaper,
  // Gift, party popper and confetti have no good Lucide equivalent and fall back to the original emoji
  '🏆': Trophy,
  '🥇': Medal,
  '🎖️': Medal,
  '🎖': Medal,
  '🚦': AlertTriangle,
  '⚠️': AlertTriangle,
  '⚠': AlertTriangle,
  '❓': HelpCircle,
  '❔': HelpCircle,
  '❗': AlertCircle,
  '❕': AlertCircle,
  'ℹ️': Info,
  'ℹ': Info,
};

const VS16 = '️';

/** Returns the Lucide icon component on a hit, or null on a miss so the render layer falls back to the emoji. */
export function lucideForEmoji(emoji: string): LucideIcon | null {
  if (!emoji) return null;
  return MAPPING[emoji] ?? MAPPING[emoji.replaceAll(VS16, '')] ?? null;
}
