package ai.oriveo.community.core.data.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Upsert
import ai.oriveo.community.core.data.entity.McpConnectionStateEntity
import ai.oriveo.community.core.data.entity.McpConversationSwitchEntity
import ai.oriveo.community.core.data.entity.McpServerEntity
import ai.oriveo.community.core.data.entity.McpStepPayloadEntity
import ai.oriveo.community.core.data.entity.McpToolPermissionEntity
import ai.oriveo.community.core.data.entity.McpToolSnapshotEntity

/**
 * Result of [McpServerDao.insertWithinLimit]. Hitting the limit and a slug collision are both user-correctable states,
 * so they are reported as values instead of native constraint exceptions.
 */
enum class McpServerInsertOutcome { Inserted, LimitReached, SlugConflict }

/** Result of [McpServerDao.insertAddition]. */
sealed class McpServerAdditionOutcome {
    /** Written; [slug] is the unique slug generated inside the transaction. */
    data class Inserted(val slug: String) : McpServerAdditionOutcome()
    data object LimitReached : McpServerAdditionOutcome()

    /** The primary key already exists. The existing row is left untouched. */
    data object ServerExists : McpServerAdditionOutcome()
}

/**
 * DAO for the local tables backing remote MCP servers.
 *
 * Every statement filters by `accountId`, like the other DAOs of this database. Every "check, then write" combination
 * (limit + unique slug + insert, removal + cascade) runs inside a `@Transaction`; otherwise two concurrent additions
 * can both pass the limit, and a removal killed halfway leaves orphaned permission rows.
 */
@Dao
interface McpServerDao {

    // ── Server records ─────────────────────────────────────

    @Query("SELECT * FROM mcp_server WHERE accountId = :accountId ORDER BY createdAt ASC, id ASC")
    suspend fun getAll(accountId: String): List<McpServerEntity>

    @Query("SELECT * FROM mcp_server WHERE accountId = :accountId AND id = :id COLLATE NOCASE")
    suspend fun getById(accountId: String, id: String): McpServerEntity?

    /**
     * Counts only rows whose `authKind` is recognized. Unrecognized rows (written by a newer version of the app) are
     * skipped on read, so the user can neither see nor delete them; counting them toward the limit would mean "the list
     * is clearly not full, yet nothing can be added".
     */
    @Query("SELECT COUNT(*) FROM mcp_server WHERE accountId = :accountId AND authKind IN (:knownAuthKinds)")
    suspend fun countReadable(accountId: String, knownAuthKinds: List<String>): Int

    /**
     * Slug collisions are checked against **all** rows, unreadable ones included: they occupy the tool-name prefix and
     * the unique index too.
     */
    @Query("SELECT slug FROM mcp_server WHERE accountId = :accountId")
    suspend fun allSlugs(accountId: String): List<String>

    @Query("SELECT EXISTS(SELECT 1 FROM mcp_server WHERE accountId = :accountId AND slug = :slug)")
    suspend fun slugExists(accountId: String, slug: String): Boolean

    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insert(entity: McpServerEntity)

    /** The limit and slug-uniqueness checks must share one write transaction with the insert. */
    @Transaction
    suspend fun insertWithinLimit(
        entity: McpServerEntity,
        maxServers: Int,
        knownAuthKinds: List<String>,
    ): McpServerInsertOutcome {
        if (countReadable(entity.accountId, knownAuthKinds) >= maxServers) return McpServerInsertOutcome.LimitReached
        if (slugExists(entity.accountId, entity.slug)) return McpServerInsertOutcome.SlugConflict
        insert(entity)
        return McpServerInsertOutcome.Inserted
    }

    @Query("SELECT EXISTS(SELECT 1 FROM mcp_server WHERE accountId = :accountId AND id = :id COLLATE NOCASE)")
    suspend fun serverExists(accountId: String, id: String): Boolean

    /**
     * Atomic persistence for the add flow: the server record, tool snapshots, default permissions and connection state
     * are written in **one write transaction**, and any failing step rolls the whole thing back, so a process killed
     * midway never leaves half a server behind.
     *
     * The slug is generated by [slugFor] inside the transaction, de-duplicated against every slug already stored (the check and the insert must share one write transaction); the slug carried by [server] is ignored. If the
     * primary key already exists this returns [McpServerAdditionOutcome.ServerExists] and **leaves the existing row
     * untouched**.
     */
    @Transaction
    suspend fun insertAddition(
        server: McpServerEntity,
        snapshots: List<McpToolSnapshotEntity>,
        permissions: List<McpToolPermissionEntity>,
        connectionState: McpConnectionStateEntity,
        maxServers: Int,
        knownAuthKinds: List<String>,
        slugFor: (existing: Set<String>) -> String,
    ): McpServerAdditionOutcome {
        val accountId = server.accountId
        if (countReadable(accountId, knownAuthKinds) >= maxServers) return McpServerAdditionOutcome.LimitReached
        if (serverExists(accountId, server.id)) return McpServerAdditionOutcome.ServerExists
        val slug = slugFor(allSlugs(accountId).toSet())
        insert(server.copy(slug = slug))
        if (snapshots.isNotEmpty()) insertToolSnapshots(snapshots)
        permissions.forEach { upsertToolPermission(it) }
        upsertConnectionState(connectionState)
        return McpServerAdditionOutcome.Inserted(slug)
    }

    @Query("UPDATE mcp_server SET pendingAdd = 0 WHERE accountId = :accountId AND id = :id COLLATE NOCASE")
    suspend fun clearPendingAdd(accountId: String, id: String): Int

    /** Records that were never confirmed and were stored before [createdBefore] (used by the startup sweep). */
    @Query("SELECT * FROM mcp_server WHERE pendingAdd != 0 AND createdAt < :createdBefore")
    suspend fun getPendingAdds(createdBefore: Long): List<McpServerEntity>

    /**
     * The user tapped "Done" on the default-permissions review: release the tools, write the permissions and clear the
     * pending-confirmation flag in one transaction, so there is no intermediate state where the server is listed while
     * its tools are still quarantined, or the reverse. If the record is already gone (swept or abandoned) nothing is
     * written and this returns false.
     */
    @Transaction
    suspend fun confirmAddition(
        accountId: String,
        serverId: String,
        snapshots: List<McpToolSnapshotEntity>,
        permissions: List<McpToolPermissionEntity>,
    ): Boolean {
        if (!serverExists(accountId, serverId)) return false
        saveToolCatalog(accountId, serverId, snapshots, permissions)
        clearPendingAdd(accountId, serverId)
        return true
    }

    /**
     * Persists one catalog result (a confirmed change or a re-fetch) as a whole: snapshots are replaced wholesale and
     * the permissions listed in [permissions] are overwritten, in one transaction. Confirming a change can lower
     * permissions (they are only ever lowered, never raised), and lifting the quarantine must take effect together with
     * that.
     */
    @Transaction
    suspend fun saveToolCatalog(
        accountId: String,
        serverId: String,
        snapshots: List<McpToolSnapshotEntity>,
        permissions: List<McpToolPermissionEntity>,
    ) {
        deleteToolSnapshots(accountId, serverId)
        if (snapshots.isNotEmpty()) insertToolSnapshots(snapshots)
        permissions.forEach { upsertToolPermission(it) }
    }

    /** User-editable fields. **Excludes `slug`** (immutable after creation): a whole-row `@Update` would overwrite it. */
    @Query(
        "UPDATE mcp_server SET name = :name, url = :url, authKind = :authKind, localOnly = :localOnly, " +
            "iconURL = :iconURL, updatedAt = :updatedAt " +
            "WHERE accountId = :accountId AND id = :id COLLATE NOCASE",
    )
    suspend fun updateEditableFields(
        accountId: String,
        id: String,
        name: String,
        url: String,
        authKind: String,
        localOnly: Boolean,
        iconURL: String?,
        updatedAt: Long,
    ): Int

    @Query("DELETE FROM mcp_server WHERE accountId = :accountId AND id = :id COLLATE NOCASE")
    suspend fun deleteServerRow(accountId: String, id: String)

    /**
     * Removes a server: the record and the local tables keyed by `serverId` are deleted together.
     *
     * Step payloads (raw arguments and results) are deleted too; the step summaries stored on messages live outside
     * these tables and are kept.
     *
     * @return the removed record, or null if it did not exist (nothing is written in that case).
     */
    @Transaction
    suspend fun deleteServerCascade(accountId: String, id: String): McpServerEntity? {
        val existing = getById(accountId, id) ?: return null
        deleteServerRow(accountId, id)
        deleteConnectionState(accountId, id)
        deleteToolSnapshots(accountId, id)
        deleteToolPermissions(accountId, id)
        deleteConversationSwitches(accountId, id)
        deleteStepPayloadsOfServer(accountId, id)
        return existing
    }

    // ── Connection state ───────────────────────────────────

    @Upsert
    suspend fun upsertConnectionState(entity: McpConnectionStateEntity)

    @Query("SELECT * FROM mcp_connection_state WHERE accountId = :accountId AND serverId = :serverId COLLATE NOCASE")
    suspend fun getConnectionState(accountId: String, serverId: String): McpConnectionStateEntity?

    @Query("DELETE FROM mcp_connection_state WHERE accountId = :accountId AND serverId = :serverId COLLATE NOCASE")
    suspend fun deleteConnectionState(accountId: String, serverId: String)

    // ── Tool snapshots ─────────────────────────────────────

    @Query(
        "SELECT * FROM mcp_tool_snapshot WHERE accountId = :accountId AND serverId = :serverId COLLATE NOCASE " +
            "ORDER BY toolName ASC",
    )
    suspend fun getToolSnapshots(accountId: String, serverId: String): List<McpToolSnapshotEntity>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertToolSnapshots(entities: List<McpToolSnapshotEntity>)

    @Query("DELETE FROM mcp_tool_snapshot WHERE accountId = :accountId AND serverId = :serverId COLLATE NOCASE")
    suspend fun deleteToolSnapshots(accountId: String, serverId: String)

    /** Wholesale replacement: no reader may observe half a catalog between the delete and the insert. */
    @Transaction
    suspend fun replaceToolSnapshots(accountId: String, serverId: String, entities: List<McpToolSnapshotEntity>) {
        deleteToolSnapshots(accountId, serverId)
        insertToolSnapshots(entities)
    }

    @Query(
        "UPDATE mcp_tool_snapshot SET pendingReview = :pendingReview " +
            "WHERE accountId = :accountId AND serverId = :serverId COLLATE NOCASE AND toolName = :toolName",
    )
    suspend fun setToolPendingReview(accountId: String, serverId: String, toolName: String, pendingReview: Boolean)

    // ── Tool permissions ───────────────────────────────────

    @Upsert
    suspend fun upsertToolPermission(entity: McpToolPermissionEntity)

    @Query("SELECT * FROM mcp_tool_permission WHERE accountId = :accountId AND serverId = :serverId COLLATE NOCASE")
    suspend fun getToolPermissions(accountId: String, serverId: String): List<McpToolPermissionEntity>

    @Query("DELETE FROM mcp_tool_permission WHERE accountId = :accountId AND serverId = :serverId COLLATE NOCASE")
    suspend fun deleteToolPermissions(accountId: String, serverId: String)

    // ── Conversation switches ──────────────────────────────

    /** A switch that is already on keeps its `enabledAt` (it determines the order in the panel). */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertConversationSwitch(entity: McpConversationSwitchEntity)

    @Query(
        "SELECT serverId FROM mcp_conversation_switch " +
            "WHERE accountId = :accountId AND conversationId = :conversationId COLLATE NOCASE " +
            "ORDER BY enabledAt ASC, serverId ASC",
    )
    suspend fun getEnabledServerIds(accountId: String, conversationId: String): List<String>

    @Query(
        "DELETE FROM mcp_conversation_switch WHERE accountId = :accountId " +
            "AND conversationId = :conversationId COLLATE NOCASE AND serverId = :serverId COLLATE NOCASE",
    )
    suspend fun deleteConversationSwitch(accountId: String, conversationId: String, serverId: String)

    @Query("DELETE FROM mcp_conversation_switch WHERE accountId = :accountId AND serverId = :serverId COLLATE NOCASE")
    suspend fun deleteConversationSwitches(accountId: String, serverId: String)

    /**
     * When a new conversation sends its first message, moves the switches held under the draft id to the real
     * conversation id (the `enabledAt` ordering is preserved). If the target conversation already has a switch for the
     * same server that row is left alone (OR IGNORE), and [deleteSwitchesOfConversation] then clears the draft
     * leftovers.
     */
    @Query(
        "UPDATE OR IGNORE mcp_conversation_switch SET conversationId = :to " +
            "WHERE accountId = :accountId AND conversationId = :from COLLATE NOCASE",
    )
    suspend fun reassignConversationSwitches(accountId: String, from: String, to: String)

    @Query("DELETE FROM mcp_conversation_switch WHERE accountId = :accountId AND conversationId = :conversationId COLLATE NOCASE")
    suspend fun deleteSwitchesOfConversation(accountId: String, conversationId: String)

    @Transaction
    suspend fun moveConversationSwitchesToConversation(accountId: String, from: String, to: String) {
        reassignConversationSwitches(accountId, from, to)
        deleteSwitchesOfConversation(accountId, from)
    }

    // ── Step payloads ──────────────────────────────────────

    @Upsert
    suspend fun upsertStepPayload(entity: McpStepPayloadEntity)

    @Query(
        "SELECT * FROM mcp_step_payload WHERE accountId = :accountId " +
            "AND messageId = :messageId COLLATE NOCASE AND stepId = :stepId",
    )
    suspend fun getStepPayload(accountId: String, messageId: String, stepId: String): McpStepPayloadEntity?

    @Query("DELETE FROM mcp_step_payload WHERE accountId = :accountId AND serverId = :serverId COLLATE NOCASE")
    suspend fun deleteStepPayloadsOfServer(accountId: String, serverId: String)

    // Cleaning up when a message or a conversation is deleted is not done here: it is part of the delete methods of
    // `MessageDao` / `ConversationDao`, in the same transaction as deleting the rows.
}
