// Generated by shared/mcp-icons/sync.mjs; edit shared/mcp-icons/catalog.json.

const BRANDS: ReadonlyArray<{ key: string; names: readonly string[]; hosts: readonly string[] }> = [
  { key: "deepwiki", names: ["deepwiki", "deep wiki", "cognition", "devin"], hosts: ["deepwiki.com", "devin.ai", "cognition.ai"] },
  { key: "context7", names: ["context7", "context 7"], hosts: ["context7.com"] },
  { key: "github", names: ["github", "github copilot"], hosts: ["github.com", "githubcopilot.com"] },
  { key: "notion", names: ["notion"], hosts: ["notion.so", "notion.com"] },
  { key: "figma", names: ["figma"], hosts: ["figma.com"] },
  { key: "brave", names: ["brave", "brave search"], hosts: ["brave.com"] },
  { key: "tavily", names: ["tavily"], hosts: ["tavily.com"] },
  { key: "exa", names: ["exa"], hosts: ["exa.ai"] },
  { key: "firecrawl", names: ["firecrawl"], hosts: ["firecrawl.dev"] },
  { key: "jina", names: ["jina", "jina ai"], hosts: ["jina.ai"] },
  { key: "perplexity", names: ["perplexity"], hosts: ["perplexity.ai"] },
  { key: "vercel", names: ["vercel"], hosts: ["vercel.com"] },
  { key: "cloudflare", names: ["cloudflare"], hosts: ["cloudflare.com"] },
  { key: "microsoft", names: ["microsoft", "azure"], hosts: ["microsoft.com", "azure.com"] },
  { key: "googlecloud", names: ["google cloud", "gcp"], hosts: ["cloud.google.com", "googleapis.com"] },
  { key: "huggingface", names: ["hugging face", "huggingface"], hosts: ["huggingface.co"] },
  { key: "browserless", names: ["browserless"], hosts: ["browserless.io"] },
  { key: "slack", names: ["slack"], hosts: ["slack.com"] },
  { key: "linear", names: ["linear"], hosts: ["linear.app"] },
  { key: "googledrive", names: ["google drive", "gdrive"], hosts: ["drive.google.com"] },
  { key: "sentry", names: ["sentry"], hosts: ["sentry.io"] },
  { key: "stripe", names: ["stripe"], hosts: ["stripe.com"] },
  { key: "airtable", names: ["airtable"], hosts: ["airtable.com"] },
  { key: "supabase", names: ["supabase"], hosts: ["supabase.com", "supabase.co"] },
  { key: "neon", names: ["neon", "neon postgres"], hosts: ["neon.tech", "neon.com"] },
  { key: "jira", names: ["jira"], hosts: ["jira.com"] },
  { key: "atlassian", names: ["atlassian"], hosts: ["atlassian.com", "atlassian.net"] },
  { key: "dropbox", names: ["dropbox"], hosts: ["dropbox.com"] },
  { key: "docker", names: ["docker"], hosts: ["docker.com"] },
  { key: "postgresql", names: ["postgres", "postgresql"], hosts: ["postgresql.org"] },
  { key: "redis", names: ["redis"], hosts: ["redis.io", "redis.com"] },
  { key: "mongodb", names: ["mongodb", "mongo db"], hosts: ["mongodb.com", "mongodb.net"] },
  { key: "snowflake", names: ["snowflake"], hosts: ["snowflake.com"] },
  { key: "elastic", names: ["elastic", "elasticsearch"], hosts: ["elastic.co"] },
  { key: "grafana", names: ["grafana"], hosts: ["grafana.com", "grafana.net"] },
  { key: "gitlab", names: ["gitlab"], hosts: ["gitlab.com"] },
  { key: "asana", names: ["asana"], hosts: ["asana.com"] },
  { key: "todoist", names: ["todoist"], hosts: ["todoist.com"] },
  { key: "zapier", names: ["zapier"], hosts: ["zapier.com"] },
  { key: "n8n", names: ["n8n"], hosts: ["n8n.io", "n8n.cloud"] },
  { key: "wikipedia", names: ["wikipedia", "wiki"], hosts: ["wikipedia.org"] },
  { key: "gitbook", names: ["gitbook"], hosts: ["gitbook.com", "gitbook.io"] },
  { key: "confluence", names: ["confluence"], hosts: ["confluence.com"] },
  { key: "clickup", names: ["clickup", "click up"], hosts: ["clickup.com"] },
  { key: "trello", names: ["trello"], hosts: ["trello.com"] },
  { key: "zendesk", names: ["zendesk"], hosts: ["zendesk.com"] },
  { key: "intercom", names: ["intercom"], hosts: ["intercom.com", "intercom.io"] },
  { key: "shopify", names: ["shopify"], hosts: ["shopify.com", "myshopify.com"] },
  { key: "hubspot", names: ["hubspot"], hosts: ["hubspot.com"] },
  { key: "resend", names: ["resend"], hosts: ["resend.com"] },
  { key: "box", names: ["box"], hosts: ["box.com"] },
  { key: "datadog", names: ["datadog"], hosts: ["datadoghq.com", "datadoghq.eu"] },
  { key: "digitalocean", names: ["digitalocean", "digital ocean"], hosts: ["digitalocean.com"] },
  { key: "bitbucket", names: ["bitbucket"], hosts: ["bitbucket.org"] },
  { key: "mysql", names: ["mysql"], hosts: ["mysql.com"] },
  { key: "sqlite", names: ["sqlite"], hosts: ["sqlite.org"] },
  { key: "duckdb", names: ["duckdb"], hosts: ["duckdb.org"] },
  { key: "kubernetes", names: ["kubernetes", "k8s"], hosts: ["kubernetes.io"] },
  { key: "postman", names: ["postman"], hosts: ["postman.com"] },
  { key: "zoom", names: ["zoom"], hosts: ["zoom.us"] },
  { key: "obsidian", names: ["obsidian"], hosts: ["obsidian.md"] },
  { key: "algolia", names: ["algolia"], hosts: ["algolia.com", "algolia.net"] },
  { key: "netlify", names: ["netlify"], hosts: ["netlify.com"] },
];

export const mcpBrandKeys: readonly string[] = BRANDS.map((entry) => entry.key);

/** Exact name aliases or vendor host with a DNS label boundary; host takes precedence. */
export function mcpBrandKey(name: string, serverURL?: string | null): string | null {
  let host: string | null = null;
  try {
    const url = new URL(serverURL ?? '');
    if (url.protocol === 'https:') host = url.hostname.toLowerCase().replace(/\.$/, '');
  } catch { /* A name can identify a local or third party server. */ }
  const hostMatch = BRANDS.flatMap((entry) => entry.hosts.map((domain) => ({ entry, domain })))
    .filter(({ domain }) => host === domain || host?.endsWith('.' + domain))
    .sort((a, b) => b.domain.length - a.domain.length)[0];
  if (hostMatch) return hostMatch.entry.key;
  const key = name.trim().toLowerCase().replace(/[._-]+/g, ' ').replace(/\s+/g, ' ')
    .replace(/^mcp(?: server)? /, '').replace(/ (?:mcp(?: server)?|server)$/, '');
  return BRANDS.find((entry) => entry.key === key.replace(/ /g, '') || entry.names.includes(key))?.key ?? null;
}

/** Public assets are bundled by the app; they never become a record's iconURL. */
export function bundledMcpIconURL(name: string, serverURL?: string | null, dark = false): string | null {
  const key = mcpBrandKey(name, serverURL);
  return key ? '/mcp-icons/' + (dark ? 'dark' : 'light') + '/' + key + '.png' : null;
}
