import { describe, expect, it } from 'vitest';
import { browserMcpClientIdentity } from '../../../lib/core/mcp/browser-mcp-runtime';
import { GET } from '../../oauth/mcp-client.json/route';

// The CIMD client metadata document: generated by the `/oauth/mcp-client.json` route from the origin
// the request arrived at. client_id must equal the document URL character for character; that is the
// core criterion of CIMD, and clients use it as their public client_id.

async function documentFor(headers: Record<string, string>, url = 'http://localhost:3001/oauth/mcp-client.json') {
  const response = GET(new Request(url, { headers }));
  return { response, document: (await response.json()) as Record<string, unknown> };
}

describe('MCP CIMD client metadata document', () => {
  it('behind a reverse proxy (request.url is an internal address): client_id is the public document URL, public client', async () => {
    const { response, document } = await documentFor({ host: 'app.example.com', 'x-forwarded-proto': 'https' });
    expect(response.status).toBe(200);
    expect(response.headers.get('content-type')).toContain('application/json');
    expect(document.client_id).toBe('https://app.example.com/oauth/mcp-client.json');
    expect(typeof document.client_name).toBe('string');
    expect((document.client_name as string).length).toBeGreaterThan(0);
    expect(document.token_endpoint_auth_method).toBe('none');
    // The only redirect is the callback page of the origin serving the document.
    expect(document.redirect_uris).toEqual(['https://app.example.com/mcp/oauth/callback']);
    const url = new URL(document.client_id as string);
    expect(url.protocol).toBe('https:');
    expect(url.pathname.length).toBeGreaterThan(1);
  });

  it('deployed on another origin: the document follows that origin and equals, character for character, the client_id / callback address the browser uses there', async () => {
    const origin = 'https://chat.selfhosted.example';
    const { document } = await documentFor({ host: 'chat.selfhosted.example', 'x-forwarded-proto': 'https' });
    const identity = browserMcpClientIdentity(origin);
    expect(document.client_id).toBe(identity.clientMetadataDocumentUrl);
    expect(document.redirect_uris).toEqual([identity.redirectUri]);
  });

  it('current origin is not public https (localhost, private network, LAN hostname): the browser does not use CIMD', () => {
    for (const origin of ['http://localhost:3001', 'https://localhost:3001', 'https://192.168.1.20', 'https://nas', 'http://app.example.com']) {
      const identity = browserMcpClientIdentity(origin);
      expect(identity.clientMetadataDocumentUrl, origin).toBeNull();
      expect(identity.redirectUri, origin).toBe(`${origin}/mcp/oauth/callback`);
    }
  });

  it('negative: invalid characters smuggled into Host give 400 and are not written into the document', async () => {
    const { response } = await documentFor({ host: 'evil.example"/x' });
    expect(response.status).toBe(400);
  });
});
