package ai.oriveo.community.core.data.remote

import android.content.Context
import android.content.SharedPreferences
import ai.oriveo.community.core.data.dao.MetadataCacheDao
import ai.oriveo.community.core.data.entity.MetadataCacheEntity
import ai.oriveo.community.core.model.AIModel
import ai.oriveo.community.core.model.Provider
import ai.oriveo.community.core.model.ProviderKind
import ai.oriveo.community.core.provider.ProviderCatalogResolver
import ai.oriveo.community.testing.TestSharedPreferences
import io.mockk.every
import io.mockk.mockk
import java.io.File
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.TestScope
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Index + per-provider catalog views. Every assertion goes through the production path:
 * transport -> validate/expand -> lean decode -> publish -> Room rows. The only fixture is the shared
 * contract `shared/model-contracts/metadata_catalog_contract.v1.json`, generated by the server tests.
 */
@OptIn(ExperimentalCoroutinesApi::class)
class MetadataCatalogSplitTest {

    @Test
    fun `split index plus catalogs decode identically to the lean equivalent`() = runTest {
        val server = FakeSplitServer(fixture())
        val client = newClient(server, FakeRowDao(), demand(ProviderKind.OpenAI, ProviderKind.Anthropic))

        client.initialize(context())

        val lean = MetadataClient()
        lean.loadNetworkPayloadForTesting(fixture().getValue("leanEquivalent").toString(), INDEX_ETAG)
        for (kind in listOf(ProviderKind.OpenAI, ProviderKind.Anthropic)) {
            val ids = lean.providerModelIds(kind)
            assertTrue(ids.isNotEmpty())
            assertEquals(ids, client.providerModelIds(kind))
            assertEquals(lean.defaultModelId(kind), client.defaultModelId(kind))
            assertEquals(lean.validation(kind), client.validation(kind))
            assertEquals(lean.providerAttachmentSupport(kind), client.providerAttachmentSupport(kind))
            for (id in ids) {
                // Model set, pricing, capabilities, generation parameter refs and evidence projection in one pass.
                assertEquals(lean.resolveCatalogModel(id, kind), client.resolveCatalogModel(id, kind))
                assertEquals(
                    lean.capabilityActionLookup(kind, id, "generation"),
                    client.capabilityActionLookup(kind, id, "generation"),
                )
                assertEquals(lean.capabilityActionLookup(kind, id, "web"), client.capabilityActionLookup(kind, id, "web"))
            }
        }
        assertEquals(lean.relayRuntimeConfig(), client.relayRuntimeConfig())
        assertEquals(lean.listPublicProviderConfigs(), client.listPublicProviderConfigs())

        // The objects the production path produces must be right on their own too (expected values
        // come straight from the fixture tables): parametersRef dereferenced, evidence identity filled in from tree position, capabilityControls expanded.
        var checkedParameters = 0
        var checkedEvidence = 0
        var checkedControls = 0
        for ((key, kind) in listOf("openAI" to ProviderKind.OpenAI, "anthropic" to ProviderKind.Anthropic)) {
            val catalog = catalogData(key)
            val tables = catalog.getValue("tables").jsonObject
            for ((id, raw) in catalog.getValue("models").jsonObject) {
                val wire = raw.jsonObject
                val model = client.resolveCatalogModel(id, kind)!!
                val profile = (wire["profilesRef"] as? JsonPrimitive)?.content
                    ?.let { tables.getValue("profiles").jsonObject.getValue(it).jsonObject }
                val parametersRef = ((profile?.get("generation") as? JsonObject)?.get("parametersRef") as? JsonPrimitive)?.content
                if (parametersRef != null && model.profiles.generation != null) {
                    val expected = tables.getValue("generationParameters").jsonObject.getValue(parametersRef)
                        .let { it as JsonArray }.map { (it.jsonObject.getValue("id") as JsonPrimitive).content }
                    assertEquals(expected, model.profiles.generation?.parameters?.mapNotNull { it.id })
                    checkedParameters += 1
                }
                val evidence = (wire["capabilityEvidenceRef"] as? JsonPrimitive)?.content
                    ?.let { tables.getValue("capabilityEvidence").jsonObject.getValue(it).jsonObject }
                if (evidence != null) {
                    // After expanding capabilityEvidenceRef the namespace ownership must match the fixture;
                    // candidates that pass this client's source/grade allowlist get their identity from tree position.
                    val expectedKeys = (evidence.getValue("candidates") as JsonArray)
                        .map { (it.jsonObject.getValue("key") as JsonPrimitive).content }.toSet()
                    assertEquals(expectedKeys, model.capabilityEvidenceOwnedKeys)
                    assertEquals(false, model.capabilityEvidenceViewMalformed)
                    model.capabilityEvidenceCandidates.orEmpty().forEach { candidate ->
                        assertEquals(id, candidate.modelId)
                        assertEquals(INDEX_ETAG, candidate.metadataRevision)
                    }
                    checkedEvidence += 1
                }
                val controls = (wire["capabilityControlsRef"] as? JsonPrimitive)?.content
                    ?.let { tables.getValue("capabilityControls").jsonObject.getValue(it).jsonObject }
                controls?.forEach { (capability, control) ->
                    assertEquals(
                        (control.jsonObject["state"] as? JsonPrimitive)?.content,
                        client.capabilityActionLookup(kind, id, capability)?.state,
                    )
                    checkedControls += 1
                }
            }
        }
        // If the fixture ever lost these ref kinds, the loops above would run empty; they must really compare something.
        assertTrue(checkedParameters > 0)
        assertTrue(checkedEvidence > 0)
        assertTrue(checkedControls > 0)
        assertEquals(MetadataClient.CatalogLoadState.Loaded, client.catalogLoadState(ProviderKind.OpenAI))
        assertTrue(client.isSnapshotConfirmed(ProviderKind.OpenAI))
        assertEquals(MetadataClient.MetadataSource.FreshNetwork, client.metadataSource(ProviderKind.OpenAI))
    }

    @Test
    fun `matching revision sends no catalog request and 304 never rewrites stored bodies`() = runTest {
        val server = FakeSplitServer(fixture())
        val dao = FakeRowDao()
        var now = 10_000L
        val client = newClient(server, dao, demand(ProviderKind.OpenAI, ProviderKind.Anthropic), now = { now })

        client.initialize(context())
        assertEquals(listOf<String?>(null), server.indexValidators)
        assertEquals(setOf("openAI", "anthropic"), server.catalogCalls.map { it.first }.toSet())
        assertEquals(setOf("index", "catalog:openAI", "catalog:anthropic"), dao.rows.keys)
        val bodiesBefore = dao.rows.mapValues { it.value.payload }
        val upsertsBefore = dao.upsertCount

        now = 20_000L
        client.refresh()

        assertEquals(listOf(null, INDEX_ETAG), server.indexValidators)
        assertEquals(2, server.catalogCalls.size)
        assertEquals(upsertsBefore, dao.upsertCount)
        assertEquals(bodiesBefore, dao.rows.mapValues { it.value.payload })
        assertEquals(20_000L, dao.rows.getValue("index").updatedAtMs)

        // A second process hydrates from the Room rows; revisions match the index, so a cold start makes no catalog request.
        val secondServer = FakeSplitServer(fixture())
        val second = newClient(secondServer, dao, demand(ProviderKind.OpenAI, ProviderKind.Anthropic), now = { now })
        second.initialize(context())
        assertNotNull(second.resolveCatalogModel(anthropicModel, ProviderKind.Anthropic))
        assertEquals(MetadataClient.MetadataSource.CachedOffline, second.metadataSource(ProviderKind.Anthropic))
        advanceUntilIdle()
        assertEquals(listOf<String?>(INDEX_ETAG), secondServer.indexValidators)
        assertTrue(secondServer.catalogCalls.isEmpty())
        assertEquals(MetadataClient.MetadataSource.FreshNetwork, second.metadataSource(ProviderKind.Anthropic))
    }

    @Test
    fun `unresolved ref rejects the whole catalog and keeps last good`() = runTest {
        val root = fixture()
        val server = FakeSplitServer(root)
        // First generation: the openAI catalog is valid under an older revision (last good).
        server.setCatalogRevision("openAI", "sha256:previous")
        server.setModelDisplayName("openAI", intactOpenAIModel, "Mini (previous)")
        val reports = mutableListOf<Map<String, String>>()
        val client = newClient(server, FakeRowDao(), demand(ProviderKind.OpenAI), reports = reports)
        client.initialize(context())
        val lastGood = client.resolveCatalogModel(brokenOpenAIModel, ProviderKind.OpenAI)?.contentOnly()
        assertNotNull(lastGood)

        // Second generation: the index points at a new revision, but one ref in the catalog is missing from its tables.
        server.resetCatalog("openAI", negativeCase(root, "unresolvedRef").getValue("catalog").jsonObject)
        client.refresh()

        // Content is still last good; only the publication revision on evidence follows the new index.
        assertEquals(lastGood, client.resolveCatalogModel(brokenOpenAIModel, ProviderKind.OpenAI)?.contentOnly())
        // Another model with intact refs in the same catalog is not adopted on its own either: rejection covers the whole catalog.
        assertEquals(
            "Mini (previous)",
            client.resolveCatalogModel(intactOpenAIModel, ProviderKind.OpenAI)?.displayName,
        )
        assertEquals(MetadataClient.CatalogLoadState.Loaded, client.catalogLoadState(ProviderKind.OpenAI))
        assertEquals(listOf("catalog_decode"), reports.map { it["phase"] })

        // Without a last good the catalog is rejected just the same: the provider stays pending instead of "empty catalog".
        val fresh = FakeSplitServer(root)
        fresh.resetCatalog("openAI", negativeCase(root, "unresolvedRef").getValue("catalog").jsonObject)
        val coldClient = newClient(fresh, FakeRowDao(), demand(ProviderKind.OpenAI), reports = mutableListOf())
        coldClient.initialize(context())
        assertNull(coldClient.resolveCatalogModel(brokenOpenAIModel, ProviderKind.OpenAI))
        assertEquals(MetadataClient.CatalogLoadState.Pending, coldClient.catalogLoadState(ProviderKind.OpenAI))
    }

    @Test
    fun `revision mismatch refetches index once then keeps last good`() = runTest {
        val root = fixture()
        val server = FakeSplitServer(root)
        val reports = mutableListOf<Map<String, String>>()
        val client = newClient(server, FakeRowDao(), demand(ProviderKind.OpenAI), reports = reports)
        client.initialize(context())
        val lastGood = client.resolveCatalogModel(brokenOpenAIModel, ProviderKind.OpenAI)?.contentOnly()
        assertNotNull(lastGood)

        val mismatch = negativeCase(root, "revisionMismatch")
        server.setIndexRevisionOnly(
            mismatch.getValue("provider").let { (it as JsonPrimitive).content },
            (mismatch.getValue("indexCatalogRevision") as JsonPrimitive).content,
        )
        server.indexValidators.clear()
        server.catalogCalls.clear()
        client.refresh()

        // The index is fetched once more (twice in total) and the catalog tried once each; still mismatched -> keep last good and report.
        assertEquals(2, server.indexValidators.size)
        assertEquals(listOf("openAI", "openAI"), server.catalogCalls.map { it.first })
        assertEquals(lastGood, client.resolveCatalogModel(brokenOpenAIModel, ProviderKind.OpenAI)?.contentOnly())
        assertEquals(listOf("catalog_revision"), reports.map { it["phase"] })
    }

    @Test
    fun `404 catalog is never an empty catalog and pending is not a miss`() = runTest {
        val root = fixture()
        val notFound = (negativeCase(root, "unknownProvider").getValue("status") as JsonPrimitive).content.toInt()
        val server = FakeSplitServer(root)
        server.statusOverrides["anthropic"] = notFound
        val reports = mutableListOf<Map<String, String>>()
        val client = newClient(server, FakeRowDao(), demand(ProviderKind.OpenAI, ProviderKind.Anthropic), reports = reports)
        client.initialize(context())

        assertEquals(listOf("catalog_fetch" to notFound.toString()), reports.map { it["phase"] to it["status"] })
        assertEquals(MetadataClient.CatalogLoadState.Pending, client.catalogLoadState(ProviderKind.Anthropic))
        assertFalse(client.isSnapshotConfirmed(ProviderKind.Anthropic))
        assertTrue(client.isSnapshotConfirmed(ProviderKind.OpenAI))
        assertEquals(MetadataClient.MetadataSource.Unknown, client.metadataSource(ProviderKind.Anthropic))

        val provider = Provider(
            id = "anthropic-1",
            kind = ProviderKind.Anthropic,
            models = listOf(AIModel(id = anthropicModel, name = anthropicModel)),
            cachedAvailableModelCount = 7,
        )
        val resolved = ProviderCatalogResolver.resolve(provider, client)
        assertTrue(resolved.catalogPending)
        // The available count keeps its last cached value instead of dropping to 0 or to the manual-model count.
        assertEquals(7, resolved.availableModelCount)
        // Provider-level fields come from the index and work before the catalog arrives.
        assertEquals(anthropicModel, client.defaultModelId(ProviderKind.Anthropic))
    }

    @Test
    fun `pending provider fetches only its own catalog and a loaded miss is a real miss`() = runTest {
        val server = FakeSplitServer(fixture())
        val client = newClient(server, FakeRowDao(), demand(ProviderKind.OpenAI))
        client.initialize(context())
        assertEquals(listOf("openAI"), server.catalogCalls.map { it.first })
        assertFalse(client.isSnapshotConfirmed(ProviderKind.Anthropic))

        val provider = Provider(
            id = "anthropic-1",
            kind = ProviderKind.Anthropic,
            models = listOf(AIModel(id = anthropicModel, name = anthropicModel)),
        )
        assertTrue(ProviderCatalogResolver.resolve(provider, client).catalogPending)
        // Reading pending repeatedly in one round does not spin: only one single-provider fetch is queued.
        assertEquals(MetadataClient.CatalogLoadState.Pending, client.catalogLoadState(ProviderKind.Anthropic))
        advanceUntilIdle()

        assertEquals(listOf("openAI", "anthropic"), server.catalogCalls.map { it.first })
        assertEquals(1, server.indexValidators.size)
        assertEquals(MetadataClient.CatalogLoadState.Loaded, client.catalogLoadState(ProviderKind.Anthropic))
        assertTrue(client.isSnapshotConfirmed(ProviderKind.Anthropic))
        val resolved = ProviderCatalogResolver.resolve(provider, client)
        assertFalse(resolved.catalogPending)
        assertEquals(corpusModelIds("anthropic").sorted(), resolved.catalog.filter { !it.isManual }.map { it.model.id }.sorted())
        // Catalog loaded and the model truly absent: a real miss.
        assertNull(client.resolveCatalogModel("claude-not-in-catalog", ProviderKind.Anthropic))
        assertEquals(MetadataClient.CatalogLoadState.Loaded, client.catalogLoadState(ProviderKind.Anthropic))
        assertEquals(2, server.catalogCalls.size)
    }

    @Test
    fun `targeted refresh pulls the requested provider without a full reload`() = runTest {
        val server = FakeSplitServer(fixture())
        val client = newClient(server, FakeRowDao(), demand(ProviderKind.OpenAI))
        client.initialize(context())

        client.refresh(setOf(ProviderKind.Anthropic))

        assertEquals(listOf(null, INDEX_ETAG), server.indexValidators)
        // openAI's revision is unchanged, so it is not fetched again; only anthropic is added.
        assertEquals(listOf("openAI", "anthropic"), server.catalogCalls.map { it.first })
        assertNotNull(client.resolveCatalogModel(anthropicModel, ProviderKind.Anthropic))
    }

    @Test
    fun `index 400 from an old server falls back to lean`() = runTest {
        val root = fixture()
        val server = FakeSplitServer(root)
        server.indexStatusOverride = 400
        val leanBody = root.getValue("leanEquivalent").toString()
        val leanValidators = mutableListOf<String?>()
        val client = MetadataClient(
            backgroundScope = this,
            ioDispatcher = StandardTestDispatcher(testScheduler),
            metadataCacheDao = FakeRowDao(),
            metadataTransport = MetadataTransport { validator ->
                leanValidators += validator
                MetadataTransportResponse(200, "\"lean-etag\"", leanBody, leanBody.length.toLong())
            },
            metadataSplitTransport = server,
            failureReporter = { error("unexpected failure: $it") },
        )
        client.catalogDemandSupplier = { demand(ProviderKind.OpenAI) }

        client.initialize(context())

        assertEquals(listOf<String?>(null), leanValidators)
        assertTrue(server.catalogCalls.isEmpty())
        assertNotNull(client.resolveCatalogModel(anthropicModel, ProviderKind.Anthropic))
        assertEquals(MetadataClient.CatalogLoadState.Loaded, client.catalogLoadState(ProviderKind.Anthropic))
    }

    @Test
    fun `legacy lean row is last good until needed catalogs arrive then retires`() = runTest {
        val root = fixture()
        val dao = FakeRowDao()
        dao.rows[MetadataCacheEntity.SINGLETON_KEY] = legacyLeanRow(root, updatedAtMs = 0L)
        val server = FakeSplitServer(root)
        server.statusOverrides["openAI"] = 500
        val reports = mutableListOf<Map<String, String>>()
        val client = newClient(server, dao, demand(ProviderKind.OpenAI), reports = reports, now = { STALE_NOW })

        client.initialize(context())

        // The openAI catalog fetch failed: that provider keeps its last good from the old payload, and the old row stays.
        assertEquals(listOf("catalog_fetch" to "500"), reports.map { it["phase"] to it["status"] })
        assertNotNull(client.resolveCatalogModel(brokenOpenAIModel, ProviderKind.OpenAI))
        assertEquals(MetadataClient.CatalogLoadState.Loaded, client.catalogLoadState(ProviderKind.OpenAI))
        assertTrue(MetadataCacheEntity.SINGLETON_KEY in dao.rows)
        assertTrue("index" in dao.rows)

        server.statusOverrides.remove("openAI")
        client.refresh()

        assertNotNull(client.resolveCatalogModel(brokenOpenAIModel, ProviderKind.OpenAI))
        assertFalse(MetadataCacheEntity.SINGLETON_KEY in dao.rows)
        assertTrue("catalog:openAI" in dao.rows)
        // After the compatibility snapshot retires, a provider nobody needs goes back to pending, not "no models".
        assertEquals(MetadataClient.CatalogLoadState.Pending, client.catalogLoadState(ProviderKind.Anthropic))
    }

    @Test
    fun `unreadable legacy row is dropped and startup cold pulls split`() = runTest {
        val dao = FakeRowDao()
        dao.rows[MetadataCacheEntity.SINGLETON_KEY] = MetadataCacheEntity(
            payload = "not-json",
            version = 1,
            contractVersion = 1,
            updatedAtMs = 1L,
        )
        val server = FakeSplitServer(fixture())
        val reports = mutableListOf<Map<String, String>>()
        val client = newClient(server, dao, demand(ProviderKind.OpenAI), reports = reports)

        client.initialize(context())

        assertEquals(listOf("cache_decode"), reports.map { it["phase"] })
        assertEquals(listOf<String?>(null), server.indexValidators)
        assertNotNull(client.resolveCatalogModel(brokenOpenAIModel, ProviderKind.OpenAI))
    }

    @Test
    fun `relay demand loads the whitelist and cross provider match only scans it`() = runTest {
        val root = fixture()
        val server = FakeSplitServer(root)
        val client = newClient(server, FakeRowDao(), MetadataClient.CatalogDemand(emptySet(), hasRelay = true))
        client.initialize(context())
        assertEquals(setOf("openAI", "anthropic"), server.catalogCalls.map { it.first }.toSet())
        assertEquals(brokenOpenAIModel, client.resolveCatalogModelAcrossProviders(brokenOpenAIModel)?.canonicalModelId)

        // The whitelist is now only anthropic: the loaded openAI catalog no longer takes part in relay matching, and a miss is still null (fail open).
        server.setWhitelist(listOf("anthropic"))
        client.refresh()
        assertNull(client.resolveCatalogModelAcrossProviders(brokenOpenAIModel))
        assertEquals(anthropicModel, client.resolveCatalogModelAcrossProviders(anthropicModel)?.canonicalModelId)
    }

    @Test
    fun `model facts sidecar keeps its own ETag and row in split mode`() = runTest {
        val factsBody = """{"code":0,"data":{"revision":"sha256:facts-fixture","facts":""" +
            """{"openAI/gpt-out-of-catalog":{"toolCall":true,"artifactHash":"sha256:x"}}}}"""
        val factsValidators = mutableListOf<String?>()
        val dao = FakeRowDao()
        val server = FakeSplitServer(fixture())
        val client = MetadataClient(
            backgroundScope = this,
            ioDispatcher = StandardTestDispatcher(testScheduler),
            metadataCacheDao = dao,
            metadataTransport = MetadataTransport { error("lean must not be requested") },
            metadataSplitTransport = server,
            modelFactsTransport = ModelFactsTransport { validator ->
                factsValidators += validator
                if (validator == "\"facts-etag\"") {
                    MetadataTransportResponse(304, validator, null, 0)
                } else {
                    MetadataTransportResponse(200, "\"facts-etag\"", factsBody, factsBody.length.toLong())
                }
            },
            failureReporter = { error("unexpected failure: $it") },
        ).also { it.catalogDemandSupplier = { demand(ProviderKind.OpenAI) } }
        client.initialize(context())
        val catalogRow = dao.rows.getValue("catalog:openAI")

        client.ensureModelFactsLoaded()
        assertEquals(true, client.modelFacts(ProviderKind.OpenAI, "gpt-out-of-catalog")?.toolCall)
        assertEquals(catalogRow, dao.rows.getValue("catalog:openAI"))
        assertTrue(dao.rows.getValue(MetadataCacheEntity.MODEL_FACTS_KEY).payload.contains("sha256:facts-fixture"))
        assertFalse(dao.rows.getValue(MetadataCacheEntity.MODEL_FACTS_KEY).payload.contains("artifactHash"))

        // A catalog refresh keeps the facts table; a new process restores the facts and their own ETag from the separate row.
        client.refresh()
        assertEquals(true, client.modelFacts(ProviderKind.OpenAI, "gpt-out-of-catalog")?.toolCall)
        val second = MetadataClient(
            backgroundScope = this,
            ioDispatcher = StandardTestDispatcher(testScheduler),
            metadataCacheDao = dao,
            metadataTransport = MetadataTransport { error("lean must not be requested") },
            metadataSplitTransport = FakeSplitServer(fixture()),
            modelFactsTransport = ModelFactsTransport { validator ->
                factsValidators += validator
                MetadataTransportResponse(304, validator, null, 0)
            },
            failureReporter = { error("unexpected failure: $it") },
        ).also { it.catalogDemandSupplier = { demand(ProviderKind.OpenAI) } }
        second.initialize(context())
        assertEquals(true, second.modelFacts(ProviderKind.OpenAI, "gpt-out-of-catalog")?.toolCall)
        second.ensureModelFactsLoaded()
        advanceUntilIdle()
        assertEquals(listOf(null), factsValidators)
    }

    // ── helpers ──

    /** metadataRevision on evidence is the publication identity (the index ETag), not catalog content. */
    private fun MetadataClient.ResolvedModelMetadata.contentOnly() = copy(
        capabilityEvidenceCandidates = capabilityEvidenceCandidates?.map { it.copy(metadataRevision = null) },
    )

    private fun TestScope.newClient(
        server: FakeSplitServer,
        dao: FakeRowDao,
        demand: MetadataClient.CatalogDemand,
        reports: MutableList<Map<String, String>>? = null,
        now: () -> Long = { 1_000L },
    ): MetadataClient = MetadataClient(
        backgroundScope = this,
        ioDispatcher = StandardTestDispatcher(testScheduler),
        metadataCacheDao = dao,
        metadataTransport = MetadataTransport { error("lean must not be requested") },
        metadataSplitTransport = server,
        nowMillis = now,
        failureReporter = { tags -> reports?.add(tags) ?: error("unexpected failure: $tags") },
    ).also { it.catalogDemandSupplier = { demand } }

    private fun demand(vararg kinds: ProviderKind) = MetadataClient.CatalogDemand(kinds.toSet(), hasRelay = false)

    private fun context(prefs: SharedPreferences = TestSharedPreferences()): Context {
        val context = mockk<Context>()
        every { context.applicationContext } returns context
        every { context.getSharedPreferences(any(), Context.MODE_PRIVATE) } returns prefs
        return context
    }

    private fun legacyLeanRow(root: JsonObject, updatedAtMs: Long): MetadataCacheEntity {
        val seed = MetadataClient()
        seed.loadNetworkPayloadForTesting(root.getValue("leanEquivalent").toString(), "\"legacy-etag\"")
        return MetadataCacheEntity(
            payload = requireNotNull(seed.encodedCachePayloadForTesting()),
            version = 86,
            contractVersion = 1,
            updatedAtMs = updatedAtMs,
        )
    }

    private fun negativeCase(root: JsonObject, name: String): JsonObject =
        root.getValue("negativeCases").jsonObject.getValue(name).jsonObject

    /** The shared fixture read as is (generated by the server tests; model entries and global fields match production). */
    private fun fixture(): JsonObject {
        val file = generateSequence(File(System.getProperty("user.dir") ?: ".").absoluteFile) { it.parentFile }
            .map { File(it, "shared/model-contracts/metadata_catalog_contract.v1.json") }
            .firstOrNull(File::exists)
            ?: error("metadata_catalog_contract.v1.json not found")
        return Json.parseToJsonElement(file.readText(Charsets.UTF_8)).jsonObject
    }

    private fun catalogData(key: String): JsonObject =
        fixture().getValue("catalogResponses").jsonObject.getValue(key).jsonObject.getValue("data").jsonObject

    private fun corpusModelIds(key: String): List<String> = catalogData(key).getValue("models").jsonObject.keys.toList()

    /** The openAI model whose ref is broken in the unresolvedRef negative case (read from the fixture, not hard-coded). */
    private val brokenOpenAIModel: String by lazy {
        val catalog = negativeCase(fixture(), "unresolvedRef").getValue("catalog").jsonObject
        val tables = catalog.getValue("tables").jsonObject
        catalog.getValue("models").jsonObject.entries.first { (_, raw) ->
            val model = raw.jsonObject
            listOf(
                "capabilityControlsRef" to "capabilityControls",
                "profilesRef" to "profiles",
                "capabilityEvidenceRef" to "capabilityEvidence",
            ).any { (field, table) ->
                val ref = (model[field] as? JsonPrimitive)?.content ?: return@any false
                tables[table]?.jsonObject?.containsKey(ref) != true
            }
        }.key
    }

    /** Another openAI model in the same negative-case catalog whose refs are intact. */
    private val intactOpenAIModel: String by lazy { corpusModelIds("openAI").first { it != brokenOpenAIModel } }

    private val anthropicModel: String by lazy { corpusModelIds("anthropic").first() }

    /** Server double: index and catalogs each carry an ETag; a matching If-None-Match returns 304. */
    private class FakeSplitServer(root: JsonObject) : MetadataSplitTransport {
        private var index: JsonObject = root.getValue("indexResponse").jsonObject
        private val catalogs: MutableMap<String, JsonObject> = root.getValue("catalogResponses").jsonObject
            .mapValues { (_, value) -> value.jsonObject.getValue("data").jsonObject }
            .toMutableMap()
        private var indexGeneration = 0
        val indexValidators = mutableListOf<String?>()
        val catalogCalls = mutableListOf<Pair<String, String?>>()
        val statusOverrides = mutableMapOf<String, Int>()
        var indexStatusOverride: Int? = null

        private fun indexETag() = if (indexGeneration == 0) INDEX_ETAG else "\"index-$indexGeneration\""
        private fun catalogETag(key: String) = "\"catalog-$key-${revisionOf(catalogs.getValue(key))}\""
        private fun revisionOf(data: JsonObject) = (data.getValue("catalogRevision") as JsonPrimitive).content

        override suspend fun fetchIndex(ifNoneMatch: String?): MetadataTransportResponse {
            indexValidators += ifNoneMatch
            indexStatusOverride?.let { return MetadataTransportResponse(it, null, null, 0) }
            if (ifNoneMatch == indexETag()) return MetadataTransportResponse(304, indexETag(), null, 0)
            val body = index.toString()
            return MetadataTransportResponse(200, indexETag(), body, body.length.toLong())
        }

        override suspend fun fetchCatalog(provider: String, ifNoneMatch: String?): MetadataTransportResponse {
            catalogCalls += provider to ifNoneMatch
            statusOverrides[provider]?.let { return MetadataTransportResponse(it, null, null, 0) }
            val data = catalogs[provider] ?: return MetadataTransportResponse(404, null, null, 0)
            val eTag = catalogETag(provider)
            if (ifNoneMatch == eTag) return MetadataTransportResponse(304, eTag, null, 0)
            val body = JsonObject(mapOf("code" to JsonPrimitive(0), "data" to data, "message" to JsonPrimitive("ok"))).toString()
            return MetadataTransportResponse(200, eTag, body, body.length.toLong())
        }

        /** Changes the catalog and the revision the index lists for it together (one server snapshot change). */
        fun setCatalogRevision(key: String, revision: String) {
            catalogs[key] = JsonObject(catalogs.getValue(key) + ("catalogRevision" to JsonPrimitive(revision)))
            setIndexRevisionOnly(key, revision)
        }

        fun setModelDisplayName(key: String, modelId: String, displayName: String) {
            val data = catalogs.getValue(key)
            val models = data.getValue("models").jsonObject
            val model = models.getValue(modelId).jsonObject
            catalogs[key] = JsonObject(
                data + ("models" to JsonObject(models + (modelId to JsonObject(model + ("displayName" to JsonPrimitive(displayName)))))),
            )
        }

        fun resetCatalog(key: String, data: JsonObject) {
            catalogs[key] = data
            setIndexRevisionOnly(key, revisionOf(data))
        }

        fun setIndexRevisionOnly(key: String, revision: String) {
            editIndexData { data ->
                val providers = data.getValue("providers").jsonObject
                val provider = providers.getValue(key).jsonObject
                data + ("providers" to JsonObject(providers + (key to JsonObject(provider + ("catalogRevision" to JsonPrimitive(revision))))))
            }
        }

        fun setWhitelist(keys: List<String>) {
            editIndexData { data ->
                data + ("relayRuntimeConfig" to JsonObject(mapOf("officialProviderWhitelist" to JsonArray(keys.map(::JsonPrimitive)))))
            }
        }

        private fun editIndexData(edit: (JsonObject) -> Map<String, JsonElement>) {
            val data = index.getValue("data").jsonObject
            index = JsonObject(index + ("data" to JsonObject(edit(data))))
            indexGeneration += 1
        }
    }

    /** Multi-row Room double with the production DAO's semantics (one row per key, substr chunks, touch updates only the timestamp). */
    private class FakeRowDao : MetadataCacheDao {
        val rows = linkedMapOf<String, MetadataCacheEntity>()
        var upsertCount = 0

        override suspend fun payloadLength(key: String): Int? =
            rows[key]?.payload?.let { it.codePointCount(0, it.length) }

        override suspend fun payloadChunk(start: Int, count: Int, key: String): String? {
            val payload = rows[key]?.payload ?: return null
            val total = payload.codePointCount(0, payload.length)
            val startIndex = (start - 1).coerceIn(0, total)
            val endIndex = (startIndex + count).coerceAtMost(total)
            return payload.substring(
                payload.offsetByCodePoints(0, startIndex),
                payload.offsetByCodePoints(0, endIndex),
            )
        }

        override suspend fun upsert(entity: MetadataCacheEntity) {
            upsertCount += 1
            rows[entity.key] = entity
        }

        override suspend fun updatedAtMs(key: String): Long? = rows[key]?.updatedAtMs

        override suspend fun touch(key: String, updatedAtMs: Long): Int {
            val row = rows[key] ?: return 0
            rows[key] = row.copy(updatedAtMs = updatedAtMs)
            return 1
        }

        override suspend fun delete(key: String) {
            rows.remove(key)
        }

        override suspend fun deleteAllExcept(keep: String) {
            rows.keys.retainAll { it == keep }
        }

        override suspend fun clear() {
            rows.clear()
        }
    }

    private companion object {
        const val INDEX_ETAG = "\"index-0\""
        const val STALE_NOW = 10L * 24 * 60 * 60 * 1000
    }
}
