import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

// One catalog owns matching and packaged assets for all three clients.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const source = path.join(root, 'shared/mcp-icons');
const { entries } = JSON.parse(fs.readFileSync(path.join(source, 'catalog.json'), 'utf8'));
const require = createRequire(import.meta.url);
const sharp = require(path.join(root, 'web/node_modules/sharp'));
const check = process.argv.includes('--check');
const outputs = new Map();
const banner = '// Generated by shared/mcp-icons/sync.mjs; edit shared/mcp-icons/catalog.json.\n';
const strings = (values) => values.map((value) => JSON.stringify(value)).join(', ');
const assetName = (key) => `McpBrand_${key}`;
const android = 'android/app/src/main';
const ios = 'ios/Oriveo/Oriveo';
const web = 'web';

for (const entry of entries) {
  if (!/^[a-z][a-z0-9]*$/.test(entry.key)) throw new Error(`Invalid brand key: ${entry.key}`);
  for (const theme of ['light', 'dark']) {
    const bytes = fs.readFileSync(path.join(source, theme, `${entry.key}.png`));
    const metadata = await sharp(bytes).metadata();
    await sharp(bytes).raw().toBuffer();
    if (!metadata.width || !metadata.height || !metadata.hasAlpha) throw new Error(`Invalid transparent image: ${entry.key}/${theme}`);
    if (!bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) throw new Error(`Invalid PNG: ${entry.key}`);
    outputs.set(`${web}/apps/app/public/mcp-icons/${theme}/${entry.key}.png`, bytes);
    outputs.set(`${android}/res/drawable-nodpi/mcp_brand_${entry.key}_${theme}.png`, bytes);
    outputs.set(`${ios}/Assets.xcassets/${assetName(entry.key)}.imageset/${theme}.png`, bytes);
  }
  outputs.set(`${ios}/Assets.xcassets/${assetName(entry.key)}.imageset/Contents.json`, JSON.stringify({
    images: [
      { filename: 'light.png', idiom: 'universal' },
      { filename: 'dark.png', idiom: 'universal', appearances: [{ appearance: 'luminosity', value: 'dark' }] },
    ], info: { author: 'xcode', version: 1 },
  }, null, 2) + '\n');
}

outputs.set(`${web}/packages/core/src/mcp/mcp-icons.ts`, banner + `
const BRANDS: ReadonlyArray<{ key: string; names: readonly string[]; hosts: readonly string[] }> = [
${entries.map(e => `  { key: ${JSON.stringify(e.key)}, names: [${strings(e.names)}], hosts: [${strings(e.hosts)}] },`).join('\n')}
];

export const mcpBrandKeys: readonly string[] = BRANDS.map((entry) => entry.key);

/** Exact name aliases or vendor host with a DNS label boundary; host takes precedence. */
export function mcpBrandKey(name: string, serverURL?: string | null): string | null {
  let host: string | null = null;
  try {
    const url = new URL(serverURL ?? '');
    if (url.protocol === 'https:') host = url.hostname.toLowerCase().replace(/\\.$/, '');
  } catch { /* A name can identify a local or third party server. */ }
  const hostMatch = BRANDS.flatMap((entry) => entry.hosts.map((domain) => ({ entry, domain })))
    .filter(({ domain }) => host === domain || host?.endsWith('.' + domain))
    .sort((a, b) => b.domain.length - a.domain.length)[0];
  if (hostMatch) return hostMatch.entry.key;
  const key = name.trim().toLowerCase().replace(/[._-]+/g, ' ').replace(/\\s+/g, ' ')
    .replace(/^mcp(?: server)? /, '').replace(/ (?:mcp(?: server)?|server)$/, '');
  return BRANDS.find((entry) => entry.key === key.replace(/ /g, '') || entry.names.includes(key))?.key ?? null;
}

/** Public assets are bundled by the app; they never become a record's iconURL. */
export function bundledMcpIconURL(name: string, serverURL?: string | null, dark = false): string | null {
  const key = mcpBrandKey(name, serverURL);
  return key ? '/mcp-icons/' + (dark ? 'dark' : 'light') + '/' + key + '.png' : null;
}
`);

outputs.set(`${android}/java/ai/oriveo/community/core/mcp/McpBrandIcons.kt`, banner + `package ai.oriveo.community.core.mcp

import ai.oriveo.community.R
import java.net.URI
import java.util.Locale

object McpBrandIcons {
    private data class Brand(val key: String, val names: Set<String>, val hosts: Set<String>, val light: Int, val dark: Int)
    private val brands = listOf(
${entries.map(e => `        Brand(${JSON.stringify(e.key)}, setOf(${strings(e.names)}), setOf(${strings(e.hosts)}), R.drawable.mcp_brand_${e.key}_light, R.drawable.mcp_brand_${e.key}_dark),`).join('\n')}
    )

    val keys: List<String> get() = brands.map { it.key }

    fun key(name: String, serverUrl: String? = null): String? {
        val host = runCatching { URI(serverUrl ?: "").takeIf { it.scheme.equals("https", ignoreCase = true) }?.host?.lowercase(Locale.ROOT)?.removeSuffix(".") }.getOrNull()
        val hostMatch = brands.flatMap { brand -> brand.hosts.map { brand to it } }
            .filter { (_, domain) -> host == domain || host?.endsWith("." + domain) == true }
            .maxByOrNull { (_, domain) -> domain.length }
        if (hostMatch != null) return hostMatch.first.key
        val normalized = name.trim().lowercase(Locale.ROOT).replace(Regex("[._-]+"), " ").replace(Regex("\\\\s+"), " ")
            .replace(Regex("^mcp(?: server)? "), "").replace(Regex(" (?:mcp(?: server)?|server)$"), "")
        return brands.firstOrNull { normalized == it.key || normalized.replace(" ", "") == it.key || normalized in it.names }?.key
    }

    fun drawable(name: String, serverUrl: String? = null, dark: Boolean = false): Int? {
        val key = key(name, serverUrl) ?: return null
        val brand = brands.first { it.key == key }
        return if (dark) brand.dark else brand.light
    }
}
`);;

outputs.set(`${ios}/Core/MCP/McpBrandIcons.swift`, banner + `import Foundation

nonisolated enum McpBrandIcons {
    private struct Brand {
        let key: String
        let names: Set<String>
        let hosts: Set<String>
    }
    private static let brands: [Brand] = [
${entries.map(e => `        Brand(key: ${JSON.stringify(e.key)}, names: [${strings(e.names)}], hosts: [${strings(e.hosts)}]),`).join('\n')}
    ]

    static var keys: [String] { brands.map(\\.key) }

    static func key(name: String, serverURL: String? = nil) -> String? {
        let url = serverURL.flatMap { URL(string: $0) }
        let host = url?.scheme?.lowercased() == "https" ? url?.host?.lowercased().replacingOccurrences(of: "\\\\.$", with: "", options: .regularExpression) : nil
        let match = brands.flatMap { brand in brand.hosts.map { (brand, $0) } }
            .filter { host == $0.1 || host?.hasSuffix("." + $0.1) == true }
            .max { $0.1.count < $1.1.count }
        if let match { return match.0.key }
        let normalized = name.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
            .replacingOccurrences(of: "[._-]+", with: " ", options: .regularExpression)
            .replacingOccurrences(of: "\\\\s+", with: " ", options: .regularExpression)
            .replacingOccurrences(of: "^mcp(?: server)? ", with: "", options: .regularExpression)
            .replacingOccurrences(of: " (?:mcp(?: server)?|server)$", with: "", options: .regularExpression)
        return brands.first { $0.key == normalized || normalized.replacingOccurrences(of: " ", with: "") == $0.key || $0.names.contains(normalized) }?.key
    }

    static func asset(name: String, serverURL: String? = nil) -> String? {
        key(name: name, serverURL: serverURL).map { "McpBrand_" + $0 }
    }
}
`);

let mismatches = 0;
for (const [relative, content] of outputs) {
  const target = path.join(root, relative);
  const bytes = Buffer.isBuffer(content) ? content : Buffer.from(content);
  if (check) {
    if (!fs.existsSync(target) || !fs.readFileSync(target).equals(bytes)) {
      console.error(`MCP icon output differs: ${relative}`);
      mismatches++;
    }
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, bytes);
  }
}
if (mismatches) process.exit(1);
console.log(`MCP icons: ${entries.length} brands, ${outputs.size} generated files ${check ? 'verified' : 'written'}.`);
