// Generated by shared/mcp-icons/sync.mjs; edit shared/mcp-icons/catalog.json.
import Foundation

nonisolated enum McpBrandIcons {
    private struct Brand {
        let key: String
        let names: Set<String>
        let hosts: Set<String>
    }
    private static let brands: [Brand] = [
        Brand(key: "deepwiki", names: ["deepwiki", "deep wiki", "cognition", "devin"], hosts: ["deepwiki.com", "devin.ai", "cognition.ai"]),
        Brand(key: "context7", names: ["context7", "context 7"], hosts: ["context7.com"]),
        Brand(key: "github", names: ["github", "github copilot"], hosts: ["github.com", "githubcopilot.com"]),
        Brand(key: "notion", names: ["notion"], hosts: ["notion.so", "notion.com"]),
        Brand(key: "figma", names: ["figma"], hosts: ["figma.com"]),
        Brand(key: "brave", names: ["brave", "brave search"], hosts: ["brave.com"]),
        Brand(key: "tavily", names: ["tavily"], hosts: ["tavily.com"]),
        Brand(key: "exa", names: ["exa"], hosts: ["exa.ai"]),
        Brand(key: "firecrawl", names: ["firecrawl"], hosts: ["firecrawl.dev"]),
        Brand(key: "jina", names: ["jina", "jina ai"], hosts: ["jina.ai"]),
        Brand(key: "perplexity", names: ["perplexity"], hosts: ["perplexity.ai"]),
        Brand(key: "vercel", names: ["vercel"], hosts: ["vercel.com"]),
        Brand(key: "cloudflare", names: ["cloudflare"], hosts: ["cloudflare.com"]),
        Brand(key: "microsoft", names: ["microsoft", "azure"], hosts: ["microsoft.com", "azure.com"]),
        Brand(key: "googlecloud", names: ["google cloud", "gcp"], hosts: ["cloud.google.com", "googleapis.com"]),
        Brand(key: "huggingface", names: ["hugging face", "huggingface"], hosts: ["huggingface.co"]),
        Brand(key: "browserless", names: ["browserless"], hosts: ["browserless.io"]),
        Brand(key: "slack", names: ["slack"], hosts: ["slack.com"]),
        Brand(key: "linear", names: ["linear"], hosts: ["linear.app"]),
        Brand(key: "googledrive", names: ["google drive", "gdrive"], hosts: ["drive.google.com"]),
        Brand(key: "sentry", names: ["sentry"], hosts: ["sentry.io"]),
        Brand(key: "stripe", names: ["stripe"], hosts: ["stripe.com"]),
        Brand(key: "airtable", names: ["airtable"], hosts: ["airtable.com"]),
        Brand(key: "supabase", names: ["supabase"], hosts: ["supabase.com", "supabase.co"]),
        Brand(key: "neon", names: ["neon", "neon postgres"], hosts: ["neon.tech", "neon.com"]),
        Brand(key: "jira", names: ["jira"], hosts: ["jira.com"]),
        Brand(key: "atlassian", names: ["atlassian"], hosts: ["atlassian.com", "atlassian.net"]),
        Brand(key: "dropbox", names: ["dropbox"], hosts: ["dropbox.com"]),
        Brand(key: "docker", names: ["docker"], hosts: ["docker.com"]),
        Brand(key: "postgresql", names: ["postgres", "postgresql"], hosts: ["postgresql.org"]),
        Brand(key: "redis", names: ["redis"], hosts: ["redis.io", "redis.com"]),
        Brand(key: "mongodb", names: ["mongodb", "mongo db"], hosts: ["mongodb.com", "mongodb.net"]),
        Brand(key: "snowflake", names: ["snowflake"], hosts: ["snowflake.com"]),
        Brand(key: "elastic", names: ["elastic", "elasticsearch"], hosts: ["elastic.co"]),
        Brand(key: "grafana", names: ["grafana"], hosts: ["grafana.com", "grafana.net"]),
        Brand(key: "gitlab", names: ["gitlab"], hosts: ["gitlab.com"]),
        Brand(key: "asana", names: ["asana"], hosts: ["asana.com"]),
        Brand(key: "todoist", names: ["todoist"], hosts: ["todoist.com"]),
        Brand(key: "zapier", names: ["zapier"], hosts: ["zapier.com"]),
        Brand(key: "n8n", names: ["n8n"], hosts: ["n8n.io", "n8n.cloud"]),
        Brand(key: "wikipedia", names: ["wikipedia", "wiki"], hosts: ["wikipedia.org"]),
        Brand(key: "gitbook", names: ["gitbook"], hosts: ["gitbook.com", "gitbook.io"]),
        Brand(key: "confluence", names: ["confluence"], hosts: ["confluence.com"]),
        Brand(key: "clickup", names: ["clickup", "click up"], hosts: ["clickup.com"]),
        Brand(key: "trello", names: ["trello"], hosts: ["trello.com"]),
        Brand(key: "zendesk", names: ["zendesk"], hosts: ["zendesk.com"]),
        Brand(key: "intercom", names: ["intercom"], hosts: ["intercom.com", "intercom.io"]),
        Brand(key: "shopify", names: ["shopify"], hosts: ["shopify.com", "myshopify.com"]),
        Brand(key: "hubspot", names: ["hubspot"], hosts: ["hubspot.com"]),
        Brand(key: "resend", names: ["resend"], hosts: ["resend.com"]),
        Brand(key: "box", names: ["box"], hosts: ["box.com"]),
        Brand(key: "datadog", names: ["datadog"], hosts: ["datadoghq.com", "datadoghq.eu"]),
        Brand(key: "digitalocean", names: ["digitalocean", "digital ocean"], hosts: ["digitalocean.com"]),
        Brand(key: "bitbucket", names: ["bitbucket"], hosts: ["bitbucket.org"]),
        Brand(key: "mysql", names: ["mysql"], hosts: ["mysql.com"]),
        Brand(key: "sqlite", names: ["sqlite"], hosts: ["sqlite.org"]),
        Brand(key: "duckdb", names: ["duckdb"], hosts: ["duckdb.org"]),
        Brand(key: "kubernetes", names: ["kubernetes", "k8s"], hosts: ["kubernetes.io"]),
        Brand(key: "postman", names: ["postman"], hosts: ["postman.com"]),
        Brand(key: "zoom", names: ["zoom"], hosts: ["zoom.us"]),
        Brand(key: "obsidian", names: ["obsidian"], hosts: ["obsidian.md"]),
        Brand(key: "algolia", names: ["algolia"], hosts: ["algolia.com", "algolia.net"]),
        Brand(key: "netlify", names: ["netlify"], hosts: ["netlify.com"]),
    ]

    static var keys: [String] { brands.map(\.key) }

    static func key(name: String, serverURL: String? = nil) -> String? {
        let url = serverURL.flatMap { URL(string: $0) }
        let host = url?.scheme?.lowercased() == "https" ? url?.host?.lowercased().replacingOccurrences(of: "\\.$", with: "", options: .regularExpression) : nil
        let match = brands.flatMap { brand in brand.hosts.map { (brand, $0) } }
            .filter { host == $0.1 || host?.hasSuffix("." + $0.1) == true }
            .max { $0.1.count < $1.1.count }
        if let match { return match.0.key }
        let normalized = name.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
            .replacingOccurrences(of: "[._-]+", with: " ", options: .regularExpression)
            .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
            .replacingOccurrences(of: "^mcp(?: server)? ", with: "", options: .regularExpression)
            .replacingOccurrences(of: " (?:mcp(?: server)?|server)$", with: "", options: .regularExpression)
        return brands.first { $0.key == normalized || normalized.replacingOccurrences(of: " ", with: "") == $0.key || $0.names.contains(normalized) }?.key
    }

    static func asset(name: String, serverURL: String? = nil) -> String? {
        key(name: name, serverURL: serverURL).map { "McpBrand_" + $0 }
    }
}
