import 'fake-indexeddb/auto';
/**
 * @vitest-environment jsdom
 *
 * Web client contract tests for the metadata index plus per-provider catalogs.
 *
 * The only corpus is the shared fixture generated by the server tests
 * (metadata_catalog_contract.v1.json); no look-alike fixture is invented here. Both sides of the
 * equivalence check go through production decoding: the split view is assembled by refreshMetadata,
 * the lean view comes through the lean fallback after the index answers 400, and what gets compared
 * is what production APIs such as resolveCatalogModel actually return.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pruneBlobs } from '../../../infra/storage/blob-cache';

const trackEvent = vi.fn();
vi.mock('../../telemetry', () => ({
  trackEvent: (...args: unknown[]) => trackEvent(...args),
}));

interface CatalogContractFixture {
  indexResponse: { data: Record<string, unknown> & { providers: Record<string, Record<string, unknown>> } };
  catalogResponses: Record<string, { data: Record<string, unknown> & { catalogRevision: string } }>;
  leanEquivalent: { data: Record<string, unknown> & { providers: Record<string, { models: Record<string, unknown> }> } };
  negativeCases: {
    unresolvedRef: { catalog: Record<string, unknown>; provider: string };
    revisionMismatch: { indexCatalogRevision: string; provider: string };
  };
}

function loadFixture(): CatalogContractFixture {
  return JSON.parse(readFileSync(
    resolve(process.cwd(), '../../..', 'shared/model-contracts/metadata_catalog_contract.v1.json'),
    'utf8',
  )) as CatalogContractFixture;
}

/** Real model ids from the corpus. Always read them from the corpus, never hardcode them: it follows the production snapshot. */
function catalogModelIds(fixture: CatalogContractFixture, kind: string): string[] {
  return Object.keys((fixture.catalogResponses[kind].data as { models: Record<string, unknown> }).models);
}

const CORPUS = loadFixture();
const OPENAI_MODEL = catalogModelIds(CORPUS, 'openAI')[0];
const ANTHROPIC_MODEL = catalogModelIds(CORPUS, 'anthropic')[0];
const MISSING_MODEL = 'model-not-in-any-corpus-catalog';
/** A moment inside the validity window of the corpus evidence (see the equivalence test). */
const PINNED_NOW = new Date('2026-10-01T00:00:00Z');

function json(body: unknown, etag?: string, extraHeaders: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { 'Content-Type': 'application/json', ...(etag ? { ETag: etag } : {}), ...extraHeaders },
  });
}

type Route = (url: string, init?: RequestInit) => Response | Promise<Response>;

function mockFetch(route: Route) {
  return vi.spyOn(globalThis, 'fetch').mockImplementation(async (input, init) => route(String(input), init));
}

function urls(spy: ReturnType<typeof mockFetch>): string[] {
  return spy.mock.calls.map(([input]) => {
    const url = String(input);
    return url.slice(url.indexOf('/api/metadata'));
  });
}

function catalogKind(url: string): string | null {
  const match = /view=catalog&provider=([^&]+)/.exec(url);
  return match ? decodeURIComponent(match[1]) : null;
}

/** A well-behaved server that serves the index and catalogs from the fixture. */
function splitServer(fixture: CatalogContractFixture, overrides: {
  index?: () => Response;
  catalog?: (kind: string) => Response | undefined;
} = {}): Route {
  return (url) => {
    if (url.endsWith('view=index')) {
      return overrides.index?.() ?? json(fixture.indexResponse, '"index-r1"');
    }
    const kind = catalogKind(url);
    if (kind) {
      const custom = overrides.catalog?.(kind);
      if (custom) return custom;
      const catalog = fixture.catalogResponses[kind];
      if (!catalog) return new Response(null, { status: 404 });
      return json(catalog, `"catalog-${kind}"`, { 'X-Metadata-Catalog-Revision': catalog.data.catalogRevision });
    }
    throw new Error(`unexpected metadata request ${url}`);
  };
}

async function freshClient() {
  vi.resetModules();
  const metadata = await import('../metadata-client');
  metadata.__resetMetadataClientForTest();
  return metadata;
}

async function settle(): Promise<void> {
  // Persistence goes through requestIdleCallback/setTimeout(0); wait for it to land
  await new Promise((resolve) => setTimeout(resolve, 30));
}

async function clearCaches(): Promise<void> {
  await pruneBlobs('oriveo:metadata:', []);
  localStorage.clear();
}

describe('metadata index + per-provider catalog', () => {
  beforeEach(async () => {
    vi.restoreAllMocks();
    trackEvent.mockClear();
    await settle();
    await clearCaches();
  });

  afterEach(async () => {
    vi.useRealTimers();
    await settle();
    await clearCaches();
  });

  it('expands index + catalogs into exactly leanEquivalent (apart from view)', async () => {
    const fixture = loadFixture();
    const split = await import('../metadata-split');
    const index = fixture.indexResponse.data;
    expect(split.isMetadataIndexPayload(index)).toBe(true);
    const catalogs = new Map<string, ReturnType<typeof expandOk>>();
    function expandOk(kind: string) {
      const result = split.expandMetadataCatalog(fixture.catalogResponses[kind].data, {
        provider: kind,
        revision: split.indexCatalogRevision(index as never, kind),
      });
      if (!result.ok) throw new Error(`catalog ${kind} rejected: ${result.reason}`);
      return result.catalog;
    }
    for (const kind of Object.keys(fixture.catalogResponses)) catalogs.set(kind, expandOk(kind));

    const assembled = split.assembleLeanFromSplit(index as never, catalogs);
    const { view: _assembledView, ...assembledRest } = JSON.parse(JSON.stringify(assembled));
    const { view: _leanView, ...leanRest } = JSON.parse(JSON.stringify(fixture.leanEquivalent.data));
    expect(assembledRest).toEqual(leanRest);
  });

  it('production decoding reaches the same result for every model from the split and lean views', async () => {
    // Evidence in the corpus carries expiresAt; pin the clock inside its validity window so the
    // evidence assertions below never depend on the day the suite runs.
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(PINNED_NOW);
    const fixture = loadFixture();
    const kinds = Object.keys(fixture.leanEquivalent.data.providers);

    async function collect(metadata: Awaited<ReturnType<typeof freshClient>>) {
      const models: Record<string, unknown> = {};
      for (const kind of kinds) {
        for (const modelId of Object.keys(fixture.leanEquivalent.data.providers[kind].models)) {
          const resolved = metadata.resolveCatalogModel(modelId, kind);
          models[`${kind}/${modelId}`] = {
            resolved,
            generation: metadata.resolveGenerationProfileRef(resolved?.profiles.generation),
            pricing: metadata.lookupPricing(modelId, kind),
            capabilities: metadata.lookupCapabilities(modelId, kind),
          };
        }
      }
      const snapshot = metadata.getMetadataSnapshot();
      return {
        models,
        providers: snapshot?.providers,
        capabilityRuntime: metadata.getCapabilityRuntime(),
        whitelist: metadata.getRelayRuntimeConfig().officialProviderWhitelist,
        validation: kinds.map((kind) => metadata.getProviderValidation(kind)),
        defaults: kinds.map((kind) => metadata.getProviderDefaultModelId(kind)),
        listed: kinds.map((kind) => metadata.listProviderModelIds(kind)),
        pending: snapshot?.catalogPendingProviders ?? [],
      };
    }

    // Split view (same ETag value, so the ETag-derived metadataRevision is comparable)
    const splitFetch = mockFetch(splitServer(fixture, { index: () => json(fixture.indexResponse, '"r1"') }));
    const splitClient = await freshClient();
    splitClient.setMetadataCatalogDemandSource(() => ({ providerKinds: kinds, hasRelay: false }));
    await splitClient.refreshMetadata();
    const fromSplit = await collect(splitClient);
    // The two catalogs are fetched in parallel, in no particular order
    expect(urls(splitFetch)[0]).toBe('/api/metadata?view=index');
    expect(urls(splitFetch).slice(1).sort()).toEqual([
      '/api/metadata?view=catalog&provider=anthropic',
      '/api/metadata?view=catalog&provider=openAI',
    ]);
    splitFetch.mockRestore();
    await settle();
    await clearCaches();

    // Lean view: an older server answers the index with 400, so the client falls back to lean
    const leanFetch = mockFetch((url) => (
      url.endsWith('view=index')
        ? new Response(null, { status: 400 })
        : json(fixture.leanEquivalent, '"r1"')
    ));
    const leanClient = await freshClient();
    await leanClient.refreshMetadata();
    const fromLean = await collect(leanClient);
    expect(urls(leanFetch)).toEqual(['/api/metadata?view=index', '/api/metadata?view=lean']);

    // Objects produced by production code: the split and lean paths must match field for field
    expect(fromSplit).toEqual(fromLean);
    expect(fromSplit.pending).toEqual([]);
    // The expanded result matches the raw fields of the corpus lean equivalent (not only itself)
    const leanModel = fixture.leanEquivalent.data.providers.openAI.models[OPENAI_MODEL] as {
      capabilityControls?: unknown;
      capabilityEvidenceView?: { candidates?: Array<{ key: string }> };
      profiles?: { generation?: { parametersRef?: string } };
    };
    const produced = fromSplit.models[`openAI/${OPENAI_MODEL}`] as {
      resolved: { capabilityControls?: unknown; capabilityEvidenceCandidates?: Array<Record<string, unknown>> } | null;
      generation?: { parameters: Array<{ id: string }> };
    };
    expect(produced.resolved).not.toBeNull();
    expect(produced.resolved?.capabilityControls).toEqual(leanModel.capabilityControls);
    const leanKeys = (leanModel.capabilityEvidenceView?.candidates ?? []).map((candidate) => candidate.key);
    if (leanKeys.length > 0) {
      expect(produced.resolved?.capabilityEvidenceCandidates?.length ?? 0).toBeGreaterThan(0);
    }
    for (const candidate of produced.resolved?.capabilityEvidenceCandidates ?? []) {
      expect(leanKeys).toContain(candidate.key);
      expect(candidate).toMatchObject({ providerKind: 'openAI', modelId: OPENAI_MODEL, metadataRevision: '"r1"' });
    }
    const parametersRef = leanModel.profiles?.generation?.parametersRef;
    if (parametersRef) {
      const table = (fixture.leanEquivalent.data.generationParameterTables as Record<string, Array<{ id: string }>>)[parametersRef];
      expect(produced.generation?.parameters.map((parameter) => parameter.id)).toEqual(table.map((entry) => entry.id));
    }
  });

  it('rejects the whole catalog on an unresolved ref, keeps last-good and records a redacted diagnostic', async () => {
    const fixture = loadFixture();
    const { provider, catalog } = fixture.negativeCases.unresolvedRef;
    // last-good comes from an older lean cache (the corpus leanEquivalent as-is); the new catalog is the corpus unresolvedRef as-is
    const seeder = await freshClient();
    await seeder.__seedMetadataCacheForTest({ data: fixture.leanEquivalent.data as never, etag: '"lean-old"' });
    await settle();
    const fetchSpy = mockFetch(splitServer(fixture, {
      catalog: (kind) => (kind === provider ? json({ code: 0, data: catalog }, '"bad"') : undefined),
    }));
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: [provider], hasRelay: false }));
    await metadata.initMetadata();
    const ids = catalogModelIds(fixture, provider);
    const lastGood = ids.map((id) => metadata.resolveCatalogModel(id, provider));
    expect(lastGood.every(Boolean)).toBe(true);

    await metadata.refreshMetadata();

    expect(urls(fetchSpy).filter((url) => url.includes(`provider=${provider}`)).length).toBeGreaterThan(0);
    // Rejected as a whole: every model is still last-good, rather than dropping just the one with the broken ref
    const after = ids.map((id) => metadata.resolveCatalogModel(id, provider));
    expect(after.every(Boolean)).toBe(true);
    expect(after.map((model) => model?.capabilityControls)).toEqual(lastGood.map((model) => model?.capabilityControls));
    expect(metadata.getProviderCatalogStatus(provider)).toBe('loaded');
    expect(trackEvent).toHaveBeenCalledWith('metadata_catalog_rejected', {
      provider_kind: provider,
      reason: 'unresolved_ref',
    });
  });

  it('stays pending on an unresolved ref with no last-good, instead of treating it as an empty catalog', async () => {
    const fixture = loadFixture();
    mockFetch(splitServer(fixture, {
      catalog: (kind) => (kind === 'openAI' ? json({ data: fixture.negativeCases.unresolvedRef.catalog }) : undefined),
    }));
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: ['openAI'], hasRelay: false }));
    await metadata.refreshMetadata();

    expect(metadata.resolveCatalogModel(OPENAI_MODEL, 'openAI')).toBeNull();
    expect(metadata.getProviderCatalogStatus('openAI')).toBe('pending');
    expect(metadata.getMetadataSnapshot()?.catalogPendingProviders).toContain('openAI');
  });

  it('refetches the index once on a revision mismatch and keeps last-good when it still does not match', async () => {
    const fixture = loadFixture();
    const { indexCatalogRevision, provider } = fixture.negativeCases.revisionMismatch;
    let stale = false;
    const fetchSpy = mockFetch(splitServer(fixture, {
      index: () => {
        if (!stale) return json(fixture.indexResponse, '"index-v1"');
        const next = structuredClone(fixture.indexResponse);
        next.data.providers[provider].catalogRevision = indexCatalogRevision;
        return json(next, '"index-stale"');
      },
    }));
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: [provider], hasRelay: false }));
    await metadata.refreshMetadata();
    const lastGood = metadata.resolveCatalogModel(OPENAI_MODEL, provider);
    expect(lastGood).not.toBeNull();

    stale = true;
    fetchSpy.mockClear();
    await metadata.refreshMetadata();

    expect(urls(fetchSpy)).toEqual([
      '/api/metadata?view=index',
      `/api/metadata?view=catalog&provider=${provider}`,
      '/api/metadata?view=index',
      `/api/metadata?view=catalog&provider=${provider}`,
    ]);
    expect(metadata.resolveCatalogModel(OPENAI_MODEL, provider)?.displayName).toBe(lastGood?.displayName);
    expect(trackEvent).toHaveBeenCalledWith('metadata_catalog_rejected', {
      provider_kind: provider,
      reason: 'revision_mismatch',
    });
  });

  it('does not read a catalog 404 as an empty catalog: the provider stays pending and enabled models are not manual', async () => {
    const fixture = loadFixture();
    mockFetch(splitServer(fixture, {
      catalog: (kind) => (kind === 'anthropic' ? new Response(null, { status: 404 }) : undefined),
    }));
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: ['anthropic'], hasRelay: false }));
    await metadata.refreshMetadata();

    expect(metadata.getProviderCatalogStatus('anthropic')).toBe('pending');
    const { resolveProviderCatalog } = await import('../../providers/catalog-resolver');
    const catalog = resolveProviderCatalog({
      kind: 'anthropic',
      models: [{
        id: ANTHROPIC_MODEL,
        name: ANTHROPIC_MODEL,
        capabilities: ['text'],
        isAvailable: true,
        isDefault: true,
        isRecommended: false,
        priceTier: '',
        reasoningModeAvailable: false,
      }] as never,
      catalogModels: [],
    }, metadata.getMetadataSnapshot() as never);
    expect(catalog.catalogPending).toBe(true);
    expect(catalog.enabledModels.map((model) => model.isManual)).toEqual([false]);
    expect(trackEvent).toHaveBeenCalledWith('metadata_catalog_rejected', {
      provider_kind: 'anthropic',
      reason: 'not_found',
    });
  });

  it('makes no catalog request when revisions match the index, and an index 304 only updates timestamps', async () => {
    const fixture = loadFixture();
    let indexNotModified = false;
    const fetchSpy = mockFetch(splitServer(fixture, {
      index: () => (indexNotModified
        ? new Response(null, { status: 304 })
        : json(fixture.indexResponse, '"index-r1"')),
    }));
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: ['openAI', 'anthropic'], hasRelay: false }));
    await metadata.refreshMetadata();

    // Same index (200): neither revision changed, so the index is the only request
    fetchSpy.mockClear();
    await metadata.refreshMetadata();
    expect(urls(fetchSpy)).toEqual(['/api/metadata?view=index']);
    await settle();
    const before = await metadata.__readSplitMetadataCacheForTest();
    expect(before.index?.etag).toBe('"index-r1"');
    const catalogBefore = await before.catalog('openAI');
    expect(catalogBefore?.value.revision).toBe(fixture.catalogResponses.openAI.data.catalogRevision);

    // Index 304: sent with the previous validator, bodies are not rewritten, only the manifest timestamp moves
    indexNotModified = true;
    fetchSpy.mockClear();
    await new Promise((resolve) => setTimeout(resolve, 5));
    const revisionBefore = metadata.getCachedMetadataVersion();
    await metadata.refreshMetadata();
    await settle();
    expect(urls(fetchSpy)).toEqual(['/api/metadata?view=index']);
    expect(fetchSpy.mock.calls[0]?.[1]).toMatchObject({
      headers: expect.objectContaining({ 'If-None-Match': '"index-r1"' }),
    });
    const after = await metadata.__readSplitMetadataCacheForTest();
    expect(after.indexTimestamp).toBe(before.indexTimestamp);
    expect((await after.catalog('openAI'))?.timestamp).toBe(catalogBefore?.timestamp);
    expect(after.manifest?.indexCheckedAt).toBeGreaterThan(before.manifest?.indexCheckedAt ?? 0);
    expect(metadata.getCachedMetadataVersion()).toBe(revisionBefore);
    expect(metadata.isMetadataSnapshotConfirmed('openAI')).toBe(true);
  });

  it('restores from the split cache on cold start without requesting catalogs whose revision is unchanged', async () => {
    const fixture = loadFixture();
    const first = mockFetch(splitServer(fixture));
    let metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: ['openAI', 'anthropic'], hasRelay: false }));
    await metadata.refreshMetadata();
    await settle();
    first.mockRestore();

    // New session: a fresh cache is usable immediately and the background refresh only revalidates the index
    const second = mockFetch(splitServer(fixture, { index: () => new Response(null, { status: 304 }) }));
    metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: ['openAI', 'anthropic'], hasRelay: false }));
    await metadata.initMetadata();
    expect(metadata.resolveCatalogModel(ANTHROPIC_MODEL, 'anthropic')?.displayName).toBeDefined();
    await vi.waitFor(() => expect(metadata.isMetadataSnapshotConfirmed('anthropic')).toBe(true));
    expect(urls(second)).toEqual(['/api/metadata?view=index']);
  });

  it('migrates an older lean cache: last-good first, then index + catalogs on the next refresh, retiring the old cache', async () => {
    const fixture = loadFixture();
    const metadataForSeed = await freshClient();
    await metadataForSeed.__seedMetadataCacheForTest({ data: fixture.leanEquivalent.data as never, etag: '"lean-old"' });

    let release: () => void = () => {};
    const gate = new Promise<void>((resolve) => { release = resolve; });
    const fetchSpy = mockFetch(async (url) => {
      await gate;
      return splitServer(fixture)(url);
    });
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: ['openAI'], hasRelay: false }));
    await metadata.initMetadata();

    // Before migration: the old lean snapshot is usable as-is (every provider present, nothing pending)
    expect(metadata.resolveCatalogModel(ANTHROPIC_MODEL, 'anthropic')).not.toBeNull();
    expect(metadata.getProviderCatalogStatus('anthropic')).toBe('loaded');

    release();
    await vi.waitFor(() => expect(metadata.getProviderCatalogStatus('openAI')).toBe('loaded'));
    await vi.waitFor(() => expect(urls(fetchSpy)).toContain('/api/metadata?view=catalog&provider=openAI'));
    await settle();
    // The index request does not carry the lean validator (validators never cross views)
    expect(fetchSpy.mock.calls[0]?.[1]).not.toMatchObject({
      headers: expect.objectContaining({ 'If-None-Match': expect.anything() }),
    });
    expect(metadata.resolveCatalogModel(OPENAI_MODEL, 'openAI')).not.toBeNull();
    // After migration only needed catalogs remain; anthropic is not needed, so it is pending (not absent)
    expect(metadata.getProviderCatalogStatus('anthropic')).toBe('pending');
    expect(await metadata.__readMetadataCacheForTest()).toBeNull();
  });

  it('discards an unreadable (malformed) cache and fetches cold without blocking startup', async () => {
    const fixture = loadFixture();
    const { writeBlob } = await import('../../../infra/storage/blob-cache');
    await writeBlob('oriveo:metadata:split:c1:index', { data: 'garbage', etag: 42 });
    await writeBlob('oriveo:metadata:c1', { data: null, etag: null });
    const fetchSpy = mockFetch(splitServer(fixture));
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: ['openAI'], hasRelay: false }));

    await expect(metadata.initMetadata()).resolves.toBeUndefined();
    expect(urls(fetchSpy)[0]).toBe('/api/metadata?view=index');
    expect(metadata.resolveCatalogModel(OPENAI_MODEL, 'openAI')).not.toBeNull();
  });

  it('keeps pending apart from miss: an unloaded provider is pending and only that one is fetched; only a loaded catalog can miss', async () => {
    const fixture = loadFixture();
    const fetchSpy = mockFetch(splitServer(fixture));
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: ['openAI'], hasRelay: false }));
    await metadata.refreshMetadata();
    fetchSpy.mockClear();

    const routing = await import('../../library/routing');
    const anthropicProvider = { id: 'p-anthropic', kind: 'anthropic', models: [] } as never;
    const claude = { id: ANTHROPIC_MODEL, transport: 'anthropic_messages' } as never;

    // Not loaded: pending (not "absent from the catalog"), routing cannot decide, and this provider is not confirmed this session
    expect(metadata.getMetadataSnapshot()?.catalogPendingProviders).toEqual(['anthropic']);
    expect(metadata.isMetadataSnapshotConfirmed('anthropic')).toBe(false);
    expect(routing.metadataCanDecideRoute(anthropicProvider, claude)).toBe(false);
    expect(metadata.resolveCatalogModel(ANTHROPIC_MODEL, 'anthropic')).toBeNull();
    expect(metadata.getProviderCatalogStatus('anthropic')).toBe('pending');

    await vi.waitFor(() => expect(metadata.getProviderCatalogStatus('anthropic')).toBe('loaded'));
    // Only that provider's catalog was fetched: no index refetch and no full refresh
    expect(urls(fetchSpy)).toEqual(['/api/metadata?view=catalog&provider=anthropic']);
    expect(metadata.resolveCatalogModel(ANTHROPIC_MODEL, 'anthropic')).not.toBeNull();
    expect(metadata.isMetadataSnapshotConfirmed('anthropic')).toBe(true);

    // Loaded and really missing is a miss; a provider absent from the index is absent (and triggers no request)
    fetchSpy.mockClear();
    expect(metadata.resolveCatalogModel(MISSING_MODEL, 'openAI')).toBeNull();
    expect(metadata.getProviderCatalogStatus('openAI')).toBe('loaded');
    expect(metadata.getProviderCatalogStatus('moonshot')).toBe('absent');
    // Provider-level fields are readable from the index before the catalog loads
    expect(metadata.getProviderValidation('openAI')).toEqual(
      fixture.indexResponse.data.providers.openAI.validation,
    );
    await settle();
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it('includes the official-provider whitelist in the needed catalogs when a relay exists', async () => {
    const fixture = loadFixture();
    const fetchSpy = mockFetch(splitServer(fixture));
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: [], hasRelay: true }));
    await metadata.refreshMetadata();

    expect(urls(fetchSpy).filter((url) => catalogKind(url)).map(catalogKind).sort()).toEqual(['anthropic', 'openAI']);
    const match = metadata.resolveCatalogModelAcrossProvidersWithProvider(ANTHROPIC_MODEL);
    expect(match?.matchedProviderKind).toBe('anthropic');
  });

  it('fetches an explicitly named provider (one being added) even though it is not configured yet', async () => {
    const fixture = loadFixture();
    const fetchSpy = mockFetch(splitServer(fixture));
    const metadata = await freshClient();
    metadata.setMetadataCatalogDemandSource(() => ({ providerKinds: [], hasRelay: false }));
    await metadata.refreshMetadata({ providerKinds: ['anthropic'] });

    expect(urls(fetchSpy)).toEqual([
      '/api/metadata?view=index',
      '/api/metadata?view=catalog&provider=anthropic',
    ]);
    const { buildOfficialEnabledModels } = await import('../../providers/official-model-sync');
    const build = buildOfficialEnabledModels('anthropic', metadata.getMetadataSnapshot() as never, {});
    expect(build.models.map((model) => model.id)).toEqual([
      fixture.indexResponse.data.providers.anthropic.defaultModelId ?? ANTHROPIC_MODEL,
    ]);
    const pending = buildOfficialEnabledModels('openAI', metadata.getMetadataSnapshot() as never, {});
    expect(pending).toMatchObject({ models: [], catalogPending: true });
  });
});
